select cd.*,IAMIND.[open],BLBLadf.[open],BLBLafg.[open],BLBLa.[open],CCCCdfd.[open],
CCCCdt.[open],CLSCLja.[open],CLSCLjad.[open],ELELefg.[open],ELELe.[open],ILAILgresd.[open],
ILAILg.[open],SLSLsds.[open],SLSLs.[open],TCTCfgf.[open],TCTCf.[open],TITIhdf.[open],TITIh.[open],ETWOza.[open],
ABALPA.[open],ABIVIS.[open],ABOLYC.[open],ABPCAL.[open],ABYOTH.[open],ACCHAC.[open],ALAL.[open],ALBCAP.[open],ALCAL.[open],
ALILKA.[open],
--ALOLPA.[open],
ALSTRA.[open],ALUSTD.[open],AMANAP.[open],AMCMSH.[open],AMIFLW.[open],ANAGRA.[open],
ANITAN.[open],ANJJIV.[open],ARSLHI.[open],ARTAR.[open],ARUVEN.[open],ARWSOL.[open],ASAVAS.[open],ASHARA.[open],ASOLTA.[open],
ASQUIT.[open],ATALBH.[open],ATMARA.[open],AWINDA.[open],AXHERM.[open],AYATHW.[open],AYVTOD.[open],
BBBB.[open],BIDBI.[open],BKANBK.[open],BKENTR.[open],BKNDUS.[open],BLAIBH.[open],BLRBL.[open],BSAURU.[open],
CCBCC.[open],CCREDI.[open],CEAJFI.[open],CEELIA.[open],CENDUR.[open],CFCF.[open],CHAXMI.[open],CHCLTE.[open],
CHENSA.[open],CHTLTE.[open],CICI.[open],CKUNTE.[open],CLCL.[open],CLFCL.[open],CLGCL.[open],CLHCL.[open],CLIACL.[open],
CLPCL.[open],COADIC.[open],COARIC.[open],COEROM.[open],COESCO.[open],COINDA.[open],COLTRA.[open],COLUES.[open],
CONDOC.[open],COUDCO.[open],CPODRE.[open],CPOLCP.[open],CSCS.[open],CTSPPR.[open],CXCX.[open],DAANKB.[open],DCDC.[open],
DCMDC.[open],DERIGA.[open],DLDL.[open],DMSTER.[open],DSCNSB.[open],DSLOKI.[open],DSOLAR.[open],DYRRED.[open],EADEA.[open],
ECAJAJ.[open],ECEC.[open],ECRIEN.[open],ECSEC.[open],EDHILP.[open],EDOLYM.[open],EDVANT.[open],EEAKRA.[open],EEATAC.[open],
EEEMON.[open],EEINDT.[open],EFRIEN.[open],EGEG.[open],EIEI.[open],ELAEL.[open],ELATAS.[open],ELEEL.[open],ELHEL.[open],
ELIHOT.[open],ELINDA.[open],ELNDHO.[open],
--ELOROM.[open],
ELSWST.[open],EMAMCO.[open],EMATAC.[open],EMEGIS.[open],
EMHREE.[open],EMLKEM.[open],EMLUOR.[open],EMMBUJ.[open],EMNDIA.[open],EMRIEN.[open],EMUDAR.[open],EMUMIC.[open],
ENDANI.[open],ENIMKE.[open],ENSTRA.[open],ERAHSC.[open],ERAJAR.[open],ERANSA.[open],ERATAP.[open],ERCHAE.[open],
ERCHNE.[open],ERCONS.[open],ERFIZE.[open],ERINDC.[open],ERKPAP.[open],ERMBER.[open],ERNDUS.[open],ERORNT.[open],ESAHSE.[open],
ESARFI.[open],ESDVEN.[open],ESINCA.[open],ESITES.[open],ESRANU.[open],ETETRO.[open],ETHALE.[open],ETPICE.[open],EXENTU.[open],
EXEX.[open],EXFLEX.[open],EXOLYP.[open],EYSHOK.[open],FBJJIV.[open],FCDFCgh.[open],FCDFCghf.[open],FCFC.[open],FCNFC.[open],
FCSFC.[open],FEBILI.[open],FEDFCL.[open],FEESTL.[open],FHTFH.[open],FIANOF.[open],FLFLd.[open],FLFLdd.[open],FLIFL.[open],
FSOTIL.[open],FTSOFT.[open],FYNFY.[open],GAINAT.[open],GCNGC.[open],
--GEOFOR.[open],
GEREST.[open],GICICI.[open],GLGLs.[open],
GLGLsa.[open],GONDIG.[open],GSARTI.[open],GYSWEN.[open],GYWANE.[open],HAOBHA.[open],HCADIL.[open],HHGHH.[open],HLGHL.[open],
HMECHM.[open],IAABCO.[open],IAAMI.[open],IAANKI.[open],IAATAI.[open],IABBOT.[open],IAIIND.[open],IAINDE.[open],IAKFIN.[open],
IAKZOI.[open],IALCIN.[open],IAOALI.[open],IAOWER.[open],IARITA.[open],IASABI.[open],IATEKT.[open],IDOWER.[open],IEAHIN.[open],
IEALML.[open],IGTKPR.[open],ILEPIL.[open],ILHRIL.[open],ILIL.[open],ILMFIN.[open],ILOCIL.[open],ILOIL.[open],ILOLTE.[open],
ILRETA.[open],ILRISI.[open],IMRASI.[open],INAIN.[open],INALRA.[open],INASFI.[open],INBIN.[open],INBULH.[open],INHOLA.[open],
INICHS.[open],INMFI.[open],INNGIN.[open],INRTRA.[open],INUNDA.[open],INUPIN.[open],INUTHO.[open],IPESHI.[open],IPLGIE.[open],
--IPOCHI.[open],
ISALLI.[open],ISETRO.[open],ISIS.[open],ISORTI.[open],ISPHAS.[open],ISRIS.[open],ITHRIR.[open],ITUPRA.[open],
IVARBO.[open],KAHANU.[open],KASHOK.[open],LAAOPA.[open],LAIPLA.[open],LEFFLE.[open],LFLF.[open],LICICI.[open],LIUJAL.[open],
LLRIND.[open],LLYDUS.[open],LOPLAP.[open],LPODFR.[open],LRMMPF.[open],LSAVEL.[open],LTT.[open],LYENTU.[open],MAOCKP.[open],
MAUNPH.[open],MAUROP.[open],MCDFCA.[open],MEANFI.[open],MIKLAK.[open],MIOTHE.[open],MLEML.[open],MM.[open],MMATAC.[open],
NBNB.[open],NBNDIA.[open],NCDOW.[open],NCINDZ.[open],NDAGEI.[open],NDALKR.[open],NDARTI.[open],NDASTR.[open],NDAYMO.[open],
NDELSP.[open],NDESTL.[open],NDFBIN.[open],NDIDIL.[open],NDIIND.[open],NDINDA.[open],NDIPIN.[open],NDNGER.[open],NDODRE.[open],
NDRAJI.[open],NDSTIN.[open],NDUMMI.[open],NDUPRE.[open],NDUXIN.[open],NDXIDE.[open],NELKYL.[open],NEYNGE.[open],NGAJAJ.[open],
NGARER.[open],NGHOLA.[open],NGIAEN.[open],NGNBHO.[open],NGOMDY.[open],NGWARA.[open],NHH.[open],NIATNA.[open],NIIDHA.[open],
NKAHAB.[open],NKANDH.[open],NKBLBA.[open],NKCBBA.[open],NKCICI.[open],NKCOBA.[open],NKDFCB.[open],NKEDER.[open],NKESBA.[open],
NKKBA.[open],NKNION.[open],NKOTAK.[open],NKOUTH.[open],NKSBBA.[open],NKTKBA.[open],NKUBAN.[open],NKXISB.[open],NLVNL.[open],
NSDANI.[open],NSIEME.[open],NTAPLI.[open],NTDANI.[open],NTEQUE.[open],NTERGE.[open],NTERSI.[open],NTKCEM.[open],NTRENT.[open],
NTRIDE.[open],NTSIAN.[open],NTTARC.[open],NTYIEN.[open],NYYMPH.[open],OBOB.[open],OCARRO.[open],OCOC.[open],ODERIT.[open],
ODUBLF.[open],OGAHLO.[open],OGRLLO.[open],OLHIRL.[open],ONAJAJ.[open],ONEDIN.[open],ONIOCO.[open],ONIXON.[open],ONNRCO.[open],
ONRCON.[open],ONROMP.[open],ONUZLO.[open],OPAYER.[open],OPHOPE.[open],OPODRE.[open],ORAVIN.[open],
--ORONCO.[open],
ORVSMO.[open],
OTICHE.[open],OTREAV.[open],PCHPC.[open],PCTPC.[open],PEINPI.[open],PLPL.[open],PLPPL.[open],PLRPL.[open],PLSPL.[open],
PNIRLA.[open],POAJES.[open],RACRA.[open],RAERA.[open],RAMRIN.[open],RANCIN.[open],RAOLAR.[open],RBHILI.[open],RBRB.[open],
RCPARC.[open],RDBICA.[open],RDGUAR.[open],REHYRO.[open],REICRE.[open],REKTYR.[open],REPOLL.[open],RFALAX.[open],RFRFdg.[open],
RFRFh.[open],RGEIDE.[open],RGHARA.[open],RGINEO.[open],RIAUKR.[open],RKLENM.[open],RLBFRL.[open],RMATCO.[open],RMBCHE.[open],
RMJANT.[open],RMORNT.[open],ROHENN.[open],ROINDP.[open],ROIPRO.[open],ROODRE.[open],ROUPPE.[open],RPBCOR.[open],RPELCO.[open],
RPELTA.[open],RPINDA.[open],RSATAM.[open],RTHAMB.[open],RTLUED.[open],RTMARTg.[open],RTMARTga.[open],RTNDIA.[open],
RXCLER.[open],RYIDPA.[open],SBSB.[open],SCESC.[open],SEEAML.[open],SERSE.[open],SESE.[open],SFASF.[open],SIATAE.[open],
SLATAS.[open],SLDSL.[open],SLFSL.[open],SNRSMJ.[open],SPPOLL.[open],SSDELW.[open],SSFSS.[open],SSUESS.[open],STATAI.[open],
STBREA.[open],STUNDR.[open],STV18B.[open],SVAJAJ.[open],TBDFCF.[open],TCBTC.[open],TCMTC.[open],TCRCTC.[open],TDAICO.[open],
TDEATL.[open],TDECLT.[open],TDHOEN.[open],TDLEMB.[open],TDMAMI.[open],TDMDCL.[open],TDOSCH.[open],TDPLLT.[open],
TDUJGA.[open],TEASTY.[open],TEILLE.[open],TERAPH.[open],TIARUT.[open],TLHART.[open],TLTL.[open],TOAJAJ.[open],TOAMNA.[open],
TREEPA.[open],TSDANI.[open],TSSCOR.[open],TSTTS.[open],TVISHT.[open],TVUNTV.[open],TWONAT.[open],TYBERO.[open],
UBUB.[open],UBULFO.[open],ULAVNE.[open],ULTUL.[open],UMATAC.[open],UMATIO.[open],UNATSU.[open],URABUR.[open],URNOXL.[open],
UTONAU.[open],VNJVN.[open],VRATAM.[open],VRINDU.[open],VRVR.[open],VSLISS.[open],WRALPA.[open],XEMAXE.[open],XOELAX.[open],
XOLAXO.[open],XPCIEX.[open],YAARUR.[open],YSENKE.[open] from [dbo].[calendar_date] cd
inner join [dbo].[3MINDIA] IAMIND on cd.[date]= IAMIND.[date]
inner join [dbo].[DBL] BLBLadf on cd.[date]= BLBLadf.[date]
inner join [dbo].[UBL] BLBLafg on cd.[date]= BLBLafg.[date]
inner join [dbo].[VBL] BLBLa on cd.[date]= BLBLa.[date]
inner join [dbo].[ACC] CCCCdfd on cd.[date]= CCCCdfd.[date]
inner join [dbo].[NCC] CCCCdt on cd.[date]= CCCCdt.[date]
inner join [dbo].[HSCL] CLSCLja on cd.[date]= CLSCLja.[date]
inner join [dbo].[KSCL] CLSCLjad on cd.[date]= CLSCLjad.[date]
inner join [dbo].[BEL] ELELefg on cd.[date]= ELELefg.[date]
inner join [dbo].[PEL] ELELe on cd.[date]= ELELe.[date]
inner join [dbo].[GAIL] ILAILgresd on cd.[date]= ILAILgresd.[date]
inner join [dbo].[SAIL] ILAILg on cd.[date]= ILAILg.[date]
inner join [dbo].[FSL] SLSLsds on cd.[date]= SLSLsds.[date]
inner join [dbo].[JSL] SLSLs on cd.[date]= SLSLs.[date]
inner join [dbo].[ITC] TCTCfgf on cd.[date]= TCTCfgf.[date]
inner join [dbo].[PTC] TCTCf on cd.[date]= TCTCf.[date]
inner join [dbo].[ITI] TITIhdf on cd.[date]= TITIhdf.[date]
inner join [dbo].[LTI] TITIh on cd.[date]= TITIh.[date]
inner join [dbo].[NETWORK18] ETWOza on cd.[date]= ETWOza.[date]
inner join [dbo].[LALPATHLAB] ABALPA on cd.[date]= ABALPA.[date]
inner join [dbo].[DIVISLAB] ABIVIS on cd.[date]= ABIVIS.[date]
inner join [dbo].[POLYCAB] ABOLYC on cd.[date]= ABOLYC.[date]
inner join [dbo].[IPCALAB] ABPCAL on cd.[date]= ABPCAL.[date]
inner join [dbo].[JYOTHYLAB] ABYOTH on cd.[date]= ABYOTH.[date]
inner join [dbo].[JCHAC] ACCHAC on cd.[date]= ACCHAC.[date]
inner join [dbo].[HAL] ALAL on cd.[date]= ALAL.[date]
inner join [dbo].[ABCAPITAL] ALBCAP on cd.[date]= ALBCAP.[date]
inner join [dbo].[DCAL] ALCAL on cd.[date]= ALCAL.[date]
inner join [dbo].[NILKAMAL] ALILKA on cd.[date]= ALILKA.[date]
--inner join [dbo].[COLPAL] ALOLPA on cd.[date]= ALOLPA.[date]
inner join [dbo].[ASTRAL] ALSTRA on cd.[date]= ALSTRA.[date]
inner join [dbo].[JUSTDIAL] ALUSTD on cd.[date]= ALUSTD.[date]
inner join [dbo].[MANAPPURAM] AMANAP on cd.[date]= AMANAP.[date]
inner join [dbo].[DCMSHRIRAM] AMCMSH on cd.[date]= AMCMSH.[date]
inner join [dbo].[IIFLWAM] AMIFLW on cd.[date]= AMIFLW.[date]
inner join [dbo].[JAGRAN] ANAGRA on cd.[date]= ANAGRA.[date]
inner join [dbo].[TITAN] ANITAN on cd.[date]= ANITAN.[date]
inner join [dbo].[UJJIVAN] ANJJIV on cd.[date]= ANJJIV.[date]
inner join [dbo].[JSLHISAR] ARSLHI on cd.[date]= ARSLHI.[date]
inner join [dbo].[STAR] ARTAR on cd.[date]= ARTAR.[date]
inner join [dbo].[SUVENPHAR] ARUVEN on cd.[date]= ARUVEN.[date]
inner join [dbo].[SWSOLAR] ARWSOL on cd.[date]= ARWSOL.[date]
inner join [dbo].[AAVAS] ASAVAS on cd.[date]= ASAVAS.[date]
inner join [dbo].[BHARATRAS] ASHARA on cd.[date]= ASHARA.[date]
inner join [dbo].[VOLTAS] ASOLTA on cd.[date]= ASOLTA.[date]
inner join [dbo].[EQUITAS] ASQUIT on cd.[date]= ASQUIT.[date]
inner join [dbo].[DALBHARAT] ATALBH on cd.[date]= ATALBH.[date]
inner join [dbo].[AMARAJABAT] ATMARA on cd.[date]= ATMARA.[date]
inner join [dbo].[JINDALSAW] AWINDA on cd.[date]= AWINDA.[date]
inner join [dbo].[THERMAX] AXHERM on cd.[date]= AXHERM.[date]
inner join [dbo].[HATHWAY] AYATHW on cd.[date]= AYATHW.[date]
inner join [dbo].[TVTODAY] AYVTOD on cd.[date]= AYVTOD.[date]
inner join [dbo].[ABB] BBBB on cd.[date]= BBBB.[date]
inner join [dbo].[IDBI] BIDBI on cd.[date]= BIDBI.[date]
inner join [dbo].[CANBK] BKANBK on cd.[date]= BKANBK.[date]
inner join [dbo].[CENTRALBK] BKENTR on cd.[date]= BKENTR.[date]
inner join [dbo].[INDUSINDBK] BKNDUS on cd.[date]= BKNDUS.[date]
inner join [dbo].[VAIBHAVGBL] BLAIBH on cd.[date]= BLAIBH.[date]
inner join [dbo].[KRBL] BLRBL on cd.[date]= BLRBL.[date]
inner join [dbo].[LAURUSLABS] BSAURU on cd.[date]= BSAURU.[date]
inner join [dbo].[NBCC] CCBCC on cd.[date]= CCBCC.[date]
inner join [dbo].[CREDITACC] CCREDI on cd.[date]= CCREDI.[date]
inner join [dbo].[BAJFINANCE] CEAJFI on cd.[date]= CEAJFI.[date]
inner join [dbo].[RELIANCE] CEELIA on cd.[date]= CEELIA.[date]
inner join [dbo].[ENDURANCE] CENDUR on cd.[date]= CENDUR.[date]
inner join [dbo].[RCF] CFCF on cd.[date]= CFCF.[date]
inner join [dbo].[LAXMIMACH] CHAXMI on cd.[date]= CHAXMI.[date]
inner join [dbo].[HCLTECH] CHCLTE on cd.[date]= CHCLTE.[date]
inner join [dbo].[ZENSARTECH] CHENSA on cd.[date]= CHENSA.[date]
inner join [dbo].[STLTECH] CHTLTE on cd.[date]= CHTLTE.[date]
inner join [dbo].[SCI] CICI on cd.[date]= CICI.[date]
inner join [dbo].[SUNTECK] CKUNTE on cd.[date]= CKUNTE.[date]
inner join [dbo].[CCL] CLCL on cd.[date]= CLCL.[date]
inner join [dbo].[HFCL] CLFCL on cd.[date]= CLFCL.[date]
inner join [dbo].[CGCL] CLGCL on cd.[date]= CLGCL.[date]
inner join [dbo].[GHCL] CLHCL on cd.[date]= CLHCL.[date]
inner join [dbo].[NIACL] CLIACL on cd.[date]= CLIACL.[date]
inner join [dbo].[BPCL] CLPCL on cd.[date]= CLPCL.[date]
inner join [dbo].[RADICO] COADIC on cd.[date]= COADIC.[date]
inner join [dbo].[MARICO] COARIC on cd.[date]= COARIC.[date]
inner join [dbo].[HEROMOTOCO] COEROM on cd.[date]= COEROM.[date]
inner join [dbo].[NESCO] COESCO on cd.[date]= COESCO.[date]
inner join [dbo].[HINDALCO] COINDA on cd.[date]= COINDA.[date]
inner join [dbo].[ULTRACEMCO] COLTRA on cd.[date]= COLTRA.[date]
inner join [dbo].[BLUESTARCO] COLUES on cd.[date]= COLUES.[date]
inner join [dbo].[INDOCO] CONDOC on cd.[date]= CONDOC.[date]
inner join [dbo].[HUDCO] COUDCO on cd.[date]= COUDCO.[date]
inner join [dbo].[GODREJCP] CPODRE on cd.[date]= CPODRE.[date]
inner join [dbo].[IOLCP] CPOLCP on cd.[date]= CPOLCP.[date]
inner join [dbo].[TCS] CSCS on cd.[date]= CSCS.[date]
inner join [dbo].[PSPPROJECT] CTSPPR on cd.[date]= CTSPPR.[date]
inner join [dbo].[MCX] CXCX on cd.[date]= CXCX.[date]
inner join [dbo].[BANKBARODA] DAANKB on cd.[date]= DAANKB.[date]
inner join [dbo].[FDC] DCDC on cd.[date]= DCDC.[date]
inner join [dbo].[NMDC] DCMDC on cd.[date]= DCMDC.[date]
inner join [dbo].[BRIGADE] DERIGA on cd.[date]= DERIGA.[date]
inner join [dbo].[BDL] DLDL on cd.[date]= DLDL.[date]
inner join [dbo].[ASTERDM] DMSTER on cd.[date]= DMSTER.[date]
inner join [dbo].[TCNSBRANDS] DSCNSB on cd.[date]= DSCNSB.[date]
inner join [dbo].[ALOKINDS] DSLOKI on cd.[date]= DSLOKI.[date]
inner join [dbo].[SOLARINDS] DSOLAR on cd.[date]= DSOLAR.[date]
inner join [dbo].[DRREDDY] DYRRED on cd.[date]= DYRRED.[date]
inner join [dbo].[IDEA] EADEA on cd.[date]= EADEA.[date]
inner join [dbo].[BAJAJELEC] ECAJAJ on cd.[date]= ECAJAJ.[date]
inner join [dbo].[KEC] ECEC on cd.[date]= ECEC.[date]
inner join [dbo].[ORIENTELEC] ECRIEN on cd.[date]= ECRIEN.[date]
inner join [dbo].[ISEC] ECSEC on cd.[date]= ECSEC.[date]
inner join [dbo].[SHILPAMED] EDHILP on cd.[date]= EDHILP.[date]
inner join [dbo].[POLYMED] EDOLYM on cd.[date]= EDOLYM.[date]
inner join [dbo].[AVANTIFEED] EDVANT on cd.[date]= EDVANT.[date]
inner join [dbo].[VAKRANGEE] EEAKRA on cd.[date]= EEAKRA.[date]
inner join [dbo].[TATACOFFEE] EEATAC on cd.[date]= EEATAC.[date]
inner join [dbo].[LEMONTREE] EEEMON on cd.[date]= EEEMON.[date]
inner join [dbo].[MINDTREE] EEINDT on cd.[date]= EEINDT.[date]
inner join [dbo].[ORIENTREF] EFRIEN on cd.[date]= EFRIEN.[date]
inner join [dbo].[HEG] EGEG on cd.[date]= EGEG.[date]
inner join [dbo].[KEI] EIEI on cd.[date]= EIEI.[date]
inner join [dbo].[GAEL] ELAEL on cd.[date]= ELAEL.[date]
inner join [dbo].[TATASTEEL] ELATAS on cd.[date]= ELATAS.[date]
inner join [dbo].[ZEEL] ELEEL on cd.[date]= ELEEL.[date]
inner join [dbo].[BHEL] ELHEL on cd.[date]= ELHEL.[date]
inner join [dbo].[EIHOTEL] ELIHOT on cd.[date]= ELIHOT.[date]
inner join [dbo].[JINDALSTEL] ELINDA on cd.[date]= ELINDA.[date]
inner join [dbo].[INDHOTEL] ELNDHO on cd.[date]= ELNDHO.[date]
--inner join [dbo].[COROMANDEL] ELOROM on cd.[date]= ELOROM.[date]
inner join [dbo].[JSWSTEEL] ELSWST on cd.[date]= ELSWST.[date]
inner join [dbo].[RAMCOCEM] EMAMCO on cd.[date]= EMAMCO.[date]
inner join [dbo].[TATACHEM] EMATAC on cd.[date]= EMATAC.[date]
inner join [dbo].[AEGISCHEM] EMEGIS on cd.[date]= EMEGIS.[date]
inner join [dbo].[SHREECEM] EMHREE on cd.[date]= EMHREE.[date]
inner join [dbo].[ALKEM] EMLKEM on cd.[date]= EMLKEM.[date]
inner join [dbo].[FLUOROCHEM] EMLUOR on cd.[date]= EMLUOR.[date]
inner join [dbo].[AMBUJACEM] EMMBUJ on cd.[date]= EMMBUJ.[date]
inner join [dbo].[INDIACEM] EMNDIA on cd.[date]= EMNDIA.[date]
inner join [dbo].[ORIENTCEM] EMRIEN on cd.[date]= EMRIEN.[date]
inner join [dbo].[SUDARSCHEM] EMUDAR on cd.[date]= EMUDAR.[date]
inner join [dbo].[SUMICHEM] EMUMIC on cd.[date]= EMUMIC.[date]
inner join [dbo].[ADANIGREEN] ENDANI on cd.[date]= ENDANI.[date]
inner join [dbo].[TIMKEN] ENIMKE on cd.[date]= ENIMKE.[date]
inner join [dbo].[ASTRAZEN] ENSTRA on cd.[date]= ENSTRA.[date]
inner join [dbo].[MAHSCOOTER] ERAHSC on cd.[date]= ERAHSC.[date]
inner join [dbo].[KAJARIACER] ERAJAR on cd.[date]= ERAJAR.[date]
inner join [dbo].[KANSAINER] ERANSA on cd.[date]= ERANSA.[date]
inner join [dbo].[TATAPOWER] ERATAP on cd.[date]= ERATAP.[date]
inner join [dbo].[SCHAEFFLER] ERCHAE on cd.[date]= ERCHAE.[date]
inner join [dbo].[SCHNEIDER] ERCHNE on cd.[date]= ERCHNE.[date]
inner join [dbo].[FCONSUMER] ERCONS on cd.[date]= ERCONS.[date]
inner join [dbo].[PFIZER] ERFIZE on cd.[date]= ERFIZE.[date]
inner join [dbo].[HINDCOPPER] ERINDC on cd.[date]= ERINDC.[date]
inner join [dbo].[JKPAPER] ERKPAP on cd.[date]= ERKPAP.[date]
inner join [dbo].[AMBER] ERMBER on cd.[date]= ERMBER.[date]
inner join [dbo].[INDUSTOWER] ERNDUS on cd.[date]= ERNDUS.[date]
inner join [dbo].[TORNTPOWER] ERORNT on cd.[date]= ERORNT.[date]
inner join [dbo].[MAHSEAMLES] ESAHSE on cd.[date]= ESAHSE.[date]
inner join [dbo].[GARFIBRES] ESARFI on cd.[date]= ESARFI.[date]
inner join [dbo].[ADVENZYMES] ESDVEN on cd.[date]= ESDVEN.[date]
inner join [dbo].[FINCABLES] ESINCA on cd.[date]= ESINCA.[date]
inner join [dbo].[RITES] ESITES on cd.[date]= ESITES.[date]
inner join [dbo].[GRANULES] ESRANU on cd.[date]= ESRANU.[date]
inner join [dbo].[PETRONET] ETETRO on cd.[date]= ETETRO.[date]
inner join [dbo].[CHALET] ETHALE on cd.[date]= ETHALE.[date]
inner join [dbo].[SPICEJET] ETPICE on cd.[date]= ETPICE.[date]
inner join [dbo].[CENTURYTEX] EXENTU on cd.[date]= EXENTU.[date]
inner join [dbo].[IEX] EXEX on cd.[date]= EXEX.[date]
inner join [dbo].[UFLEX] EXFLEX on cd.[date]= EXFLEX.[date]
inner join [dbo].[POLYPLEX] EXOLYP on cd.[date]= EXOLYP.[date]
inner join [dbo].[ASHOKLEY] EYSHOK on cd.[date]= EYSHOK.[date]
inner join [dbo].[UJJIVANSFB] FBJJIV on cd.[date]= FBJJIV.[date]
inner join [dbo].[IDFC] FCDFCgh on cd.[date]= FCDFCgh.[date]
inner join [dbo].[HDFC] FCDFCghf on cd.[date]= FCDFCghf.[date]
inner join [dbo].[PFC] FCFC on cd.[date]= FCFC.[date]
inner join [dbo].[GNFC] FCNFC on cd.[date]= FCNFC.[date]
inner join [dbo].[GSFC] FCSFC on cd.[date]= FCSFC.[date]
inner join [dbo].[SBILIFE] FEBILI on cd.[date]= FEBILI.[date]
inner join [dbo].[HDFCLIFE] FEDFCL on cd.[date]= FEDFCL.[date]
inner join [dbo].[WESTLIFE] FEESTL on cd.[date]= FEESTL.[date]
inner join [dbo].[L&TFH] FHTFH on cd.[date]= FHTFH.[date]
inner join [dbo].[SANOFI] FIANOF on cd.[date]= FIANOF.[date]
inner join [dbo].[SFL] FLFLd on cd.[date]= FLFLd.[date]
inner join [dbo].[NFL] FLFLdd on cd.[date]= FLFLdd.[date]
inner join [dbo].[IIFL] FLIFL on cd.[date]= FLIFL.[date]
inner join [dbo].[MOTILALOFS] FSOTIL on cd.[date]= FSOTIL.[date]
inner join [dbo].[BSOFT] FTSOFT on cd.[date]= FTSOFT.[date]
inner join [dbo].[INFY] FYNFY on cd.[date]= FYNFY.[date]
inner join [dbo].[VINATIORGA] GAINAT on cd.[date]= GAINAT.[date]
inner join [dbo].[ONGC] GCNGC on cd.[date]= GCNGC.[date]
--inner join [dbo].[COFORGE] GEOFOR on cd.[date]= GEOFOR.[date]
inner join [dbo].[PRESTIGE] GEREST on cd.[date]= GEREST.[date]
inner join [dbo].[ICICIGI] GICICI on cd.[date]= GICICI.[date]
inner join [dbo].[MGL] GLGLs on cd.[date]= GLGLs.[date]
inner join [dbo].[IGL] GLGLsa on cd.[date]= GLGLsa.[date]
inner join [dbo].[INDIGO] GONDIG on cd.[date]= GONDIG.[date]
inner join [dbo].[AARTIDRUGS] GSARTI on cd.[date]= GSARTI.[date]
inner join [dbo].[JSWENERGY] GYSWEN on cd.[date]= GYSWEN.[date]
inner join [dbo].[SWANENERGY] GYWANE on cd.[date]= GYWANE.[date]
inner join [dbo].[SOBHA] HAOBHA on cd.[date]= HAOBHA.[date]
inner join [dbo].[CADILAHC] HCADIL on cd.[date]= HCADIL.[date]
inner join [dbo].[PGHH] HHGHH on cd.[date]= HHGHH.[date]
inner join [dbo].[PGHL] HLGHL on cd.[date]= HLGHL.[date]
inner join [dbo].[TECHM] HMECHM on cd.[date]= HMECHM.[date]
inner join [dbo].[WABCOINDIA] IAABCO on cd.[date]= IAABCO.[date]
inner join [dbo].[NAM-INDIA] IAAMI on cd.[date]= IAAMI.[date]
inner join [dbo].[BANKINDIA] IAANKI on cd.[date]= IAANKI.[date]
inner join [dbo].[BATAINDIA] IAATAI on cd.[date]= IAATAI.[date]
inner join [dbo].[ABBOTINDIA] IABBOT on cd.[date]= IABBOT.[date]
inner join [dbo].[TIINDIA] IAIIND on cd.[date]= IAIIND.[date]
inner join [dbo].[LINDEINDIA] IAINDE on cd.[date]= IAINDE.[date]
inner join [dbo].[SKFINDIA] IAKFIN on cd.[date]= IAKFIN.[date]
inner join [dbo].[AKZOINDIA] IAKZOI on cd.[date]= IAKZOI.[date]
inner join [dbo].[NLCINDIA] IALCIN on cd.[date]= IALCIN.[date]
inner join [dbo].[COALINDIA] IAOALI on cd.[date]= IAOALI.[date]
inner join [dbo].[POWERINDIA] IAOWER on cd.[date]= IAOWER.[date]
inner join [dbo].[BRITANNIA] IARITA on cd.[date]= IARITA.[date]
inner join [dbo].[ESABINDIA] IASABI on cd.[date]= IASABI.[date]
inner join [dbo].[JTEKTINDIA] IATEKT on cd.[date]= IATEKT.[date]
inner join [dbo].[POWERGRID] IDOWER on cd.[date]= IDOWER.[date]
inner join [dbo].[MAHINDCIE] IEAHIN on cd.[date]= IEAHIN.[date]
inner join [dbo].[BALMLAWRIE] IEALML on cd.[date]= IEALML.[date]
inner join [dbo].[TTKPRESTIG] IGTKPR on cd.[date]= IGTKPR.[date]
inner join [dbo].[GEPIL] ILEPIL on cd.[date]= ILEPIL.[date]
inner join [dbo].[MHRIL] ILHRIL on cd.[date]= ILHRIL.[date]
inner join [dbo].[OIL] ILIL on cd.[date]= ILIL.[date]
inner join [dbo].[JMFINANCIL] ILMFIN on cd.[date]= ILMFIN.[date]
inner join [dbo].[NOCIL] ILOCIL on cd.[date]= ILOCIL.[date]
inner join [dbo].[MOIL] ILOIL on cd.[date]= ILOIL.[date]
inner join [dbo].[KOLTEPATIL] ILOLTE on cd.[date]= ILOLTE.[date]
inner join [dbo].[FRETAIL] ILRETA on cd.[date]= ILRETA.[date]
inner join [dbo].[CRISIL] ILRISI on cd.[date]= ILRISI.[date]
inner join [dbo].[GRASIM] IMRASI on cd.[date]= IMRASI.[date]
inner join [dbo].[RAIN] INAIN on cd.[date]= INAIN.[date]
inner join [dbo].[BALRAMCHIN] INALRA on cd.[date]= INALRA.[date]
inner join [dbo].[MASFIN] INASFI on cd.[date]= INASFI.[date]
inner join [dbo].[SBIN] INBIN on cd.[date]= INBIN.[date]
inner join [dbo].[IBULHSGFIN] INBULH on cd.[date]= INBULH.[date]
inner join [dbo].[CHOLAFIN] INHOLA on cd.[date]= INHOLA.[date]
inner join [dbo].[LICHSGFIN] INICHS on cd.[date]= INICHS.[date]
inner join [dbo].[M&MFIN] INMFI on cd.[date]= INMFI.[date]
inner join [dbo].[ENGINERSIN] INNGIN on cd.[date]= INNGIN.[date]
inner join [dbo].[SRTRANSFIN] INRTRA on cd.[date]= INRTRA.[date]
inner join [dbo].[SUNDARMFIN] INUNDA on cd.[date]= INUNDA.[date]
inner join [dbo].[LUPIN] INUPIN on cd.[date]= INUPIN.[date]
inner join [dbo].[MUTHOOTFIN] INUTHO on cd.[date]= INUTHO.[date]
inner join [dbo].[GESHIP] IPESHI on cd.[date]= IPESHI.[date]
inner join [dbo].[ELGIEQUIP] IPLGIE on cd.[date]= IPLGIE.[date]
--inner join [dbo].[COCHINSHIP] IPOCHI on cd.[date]= IPOCHI.[date]
inner join [dbo].[RALLIS] ISALLI on cd.[date]= ISALLI.[date]
inner join [dbo].[METROPOLIS] ISETRO on cd.[date]= ISETRO.[date]
inner join [dbo].[SIS] ISIS on cd.[date]= ISIS.[date]
inner join [dbo].[FORTIS] ISORTI on cd.[date]= ISORTI.[date]
inner join [dbo].[MPHASIS] ISPHAS on cd.[date]= ISPHAS.[date]
inner join [dbo].[ERIS] ISRIS on cd.[date]= ISRIS.[date]
inner join [dbo].[SHRIRAMCIT] ITHRIR on cd.[date]= ITHRIR.[date]
inner join [dbo].[SUPRAJIT] ITUPRA on cd.[date]= ITUPRA.[date]
inner join [dbo].[CARBORUNIV] IVARBO on cd.[date]= IVARBO.[date]
inner join [dbo].[DHANUKA] KAHANU on cd.[date]= KAHANU.[date]
inner join [dbo].[ASHOKA] KASHOK on cd.[date]= KASHOK.[date]
inner join [dbo].[LAOPALA] LAAOPA on cd.[date]= LAAOPA.[date]
inner join [dbo].[CIPLA] LAIPLA on cd.[date]= LAIPLA.[date]
inner join [dbo].[AFFLE] LEFFLE on cd.[date]= LEFFLE.[date]
inner join [dbo].[DLF] LFLF on cd.[date]= LFLF.[date]
inner join [dbo].[ICICIPRULI] LICICI on cd.[date]= LICICI.[date]
inner join [dbo].[GUJALKALI] LIUJAL on cd.[date]= LIUJAL.[date]
inner join [dbo].[GRINDWELL] LLRIND on cd.[date]= LLRIND.[date]
inner join [dbo].[ZYDUSWELL] LLYDUS on cd.[date]= LLYDUS.[date]
inner join [dbo].[APLAPOLLO] LOPLAP on cd.[date]= LOPLAP.[date]
inner join [dbo].[GODFRYPHLP] LPODFR on cd.[date]= LPODFR.[date]
inner join [dbo].[GMMPFAUDLR] LRMMPF on cd.[date]= LRMMPF.[date]
inner join [dbo].[HAVELLS] LSAVEL on cd.[date]= LSAVEL.[date]
inner join [dbo].[LT] LTT on cd.[date]= LTT.[date]
inner join [dbo].[CENTURYPLY] LYENTU on cd.[date]= LYENTU.[date]
inner join [dbo].[WOCKPHARMA] MAOCKP on cd.[date]= MAOCKP.[date]
inner join [dbo].[SUNPHARMA] MAUNPH on cd.[date]= MAUNPH.[date]
inner join [dbo].[AUROPHARMA] MAUROP on cd.[date]= MAUROP.[date]
inner join [dbo].[HDFCAMC] MCDFCA on cd.[date]= MCDFCA.[date]
inner join [dbo].[CANFINHOME] MEANFI on cd.[date]= MEANFI.[date]
inner join [dbo].[JKLAKSHMI] MIKLAK on cd.[date]= MIKLAK.[date]
inner join [dbo].[MOTHERSUMI] MIOTHE on cd.[date]= MIOTHE.[date]
inner join [dbo].[BEML] MLEML on cd.[date]= MLEML.[date]
inner join [dbo].[M&M] MM on cd.[date]= MM.[date]
inner join [dbo].[TATACOMM] MMATAC on cd.[date]= MMATAC.[date]
inner join [dbo].[PNB] NBNB on cd.[date]= NBNB.[date]
inner join [dbo].[INDIANB] NBNDIA on cd.[date]= NBNDIA.[date]
inner join [dbo].[MCDOWELL-N] NCDOW on cd.[date]= NCDOW.[date]
inner join [dbo].[HINDZINC] NCINDZ on cd.[date]= NCINDZ.[date]
inner join [dbo].[PAGEIND] NDAGEI on cd.[date]= NDAGEI.[date]
inner join [dbo].[BALKRISIND] NDALKR on cd.[date]= NDALKR.[date]
inner join [dbo].[AARTIIND] NDARTI on cd.[date]= NDARTI.[date]
inner join [dbo].[CASTROLIND] NDASTR on cd.[date]= NDASTR.[date]
inner join [dbo].[RAYMOND] NDAYMO on cd.[date]= NDAYMO.[date]
inner join [dbo].[WELSPUNIND] NDELSP on cd.[date]= NDELSP.[date]
inner join [dbo].[NESTLEIND] NDESTL on cd.[date]= NDESTL.[date]
inner join [dbo].[IFBIND] NDFBIN on cd.[date]= NDFBIN.[date]
inner join [dbo].[PIDILITIND] NDIDIL on cd.[date]= NDIDIL.[date]
inner join [dbo].[PIIND] NDIIND on cd.[date]= NDIIND.[date]
inner join [dbo].[MINDAIND] NDINDA on cd.[date]= NDINDA.[date]
inner join [dbo].[VIPIND] NDIPIN on cd.[date]= NDIPIN.[date]
inner join [dbo].[INGERRAND] NDNGER on cd.[date]= NDNGER.[date]
inner join [dbo].[GODREJIND] NDODRE on cd.[date]= NDODRE.[date]
inner join [dbo].[PRAJIND] NDRAJI on cd.[date]= NDRAJI.[date]
inner join [dbo].[VSTIND] NDSTIN on cd.[date]= NDSTIN.[date]
inner join [dbo].[CUMMINSIND] NDUMMI on cd.[date]= NDUMMI.[date]
inner join [dbo].[SUPREMEIND] NDUPRE on cd.[date]= NDUPRE.[date]
inner join [dbo].[LUXIND] NDUXIN on cd.[date]= NDUXIN.[date]
inner join [dbo].[EXIDEIND] NDXIDE on cd.[date]= NDXIDE.[date]
inner join [dbo].[ALKYLAMINE] NELKYL on cd.[date]= NELKYL.[date]
inner join [dbo].[SYNGENE] NEYNGE on cd.[date]= NEYNGE.[date]
inner join [dbo].[BAJAJHLDNG] NGAJAJ on cd.[date]= NGAJAJ.[date]
inner join [dbo].[CARERATING] NGARER on cd.[date]= NGARER.[date]
inner join [dbo].[CHOLAHLDNG] NGHOLA on cd.[date]= NGHOLA.[date]
inner join [dbo].[AIAENG] NGIAEN on cd.[date]= NGIAEN.[date]
inner join [dbo].[PNBHOUSING] NGNBHO on cd.[date]= NGNBHO.[date]
inner join [dbo].[BOMDYEING] NGOMDY on cd.[date]= NGOMDY.[date]
inner join [dbo].[SWARAJENG] NGWARA on cd.[date]= NGWARA.[date]
inner join [dbo].[NH] NHH on cd.[date]= NHH.[date]
inner join [dbo].[RATNAMANI] NIATNA on cd.[date]= NIATNA.[date]
inner join [dbo].[MIDHANI] NIIDHA on cd.[date]= NIIDHA.[date]
inner join [dbo].[MAHABANK] NKAHAB on cd.[date]= NKAHAB.[date]
inner join [dbo].[BANDHANBNK] NKANDH on cd.[date]= NKANDH.[date]
inner join [dbo].[RBLBANK] NKBLBA on cd.[date]= NKBLBA.[date]
inner join [dbo].[DCBBANK] NKCBBA on cd.[date]= NKCBBA.[date]
inner join [dbo].[ICICIBANK] NKCICI on cd.[date]= NKCICI.[date]
inner join [dbo].[UCOBANK] NKCOBA on cd.[date]= NKCOBA.[date]
inner join [dbo].[HDFCBANK] NKDFCB on cd.[date]= NKDFCB.[date]
inner join [dbo].[FEDERALBNK] NKEDER on cd.[date]= NKEDER.[date]
inner join [dbo].[YESBANK] NKESBA on cd.[date]= NKESBA.[date]
inner join [dbo].[J&KBANK] NKKBA on cd.[date]= NKKBA.[date]
inner join [dbo].[UNIONBANK] NKNION on cd.[date]= NKNION.[date]
inner join [dbo].[KOTAKBANK] NKOTAK on cd.[date]= NKOTAK.[date]
inner join [dbo].[SOUTHBANK] NKOUTH on cd.[date]= NKOUTH.[date]
inner join [dbo].[CSBBANK] NKSBBA on cd.[date]= NKSBBA.[date]
inner join [dbo].[KTKBANK] NKTKBA on cd.[date]= NKTKBA.[date]
inner join [dbo].[AUBANK] NKUBAN on cd.[date]= NKUBAN.[date]
inner join [dbo].[AXISBANK] NKXISB on cd.[date]= NKXISB.[date]
inner join [dbo].[RVNL] NLVNL on cd.[date]= NLVNL.[date]
inner join [dbo].[ADANITRANS] NSDANI on cd.[date]= NSDANI.[date]
inner join [dbo].[SIEMENS] NSIEME on cd.[date]= NSIEME.[date]
inner join [dbo].[CAPLIPOINT] NTAPLI on cd.[date]= NTAPLI.[date]
inner join [dbo].[ADANIENT] NTDANI on cd.[date]= NTDANI.[date]
inner join [dbo].[SEQUENT] NTEQUE on cd.[date]= NTEQUE.[date]
inner join [dbo].[BERGEPAINT] NTERGE on cd.[date]= NTERGE.[date]
inner join [dbo].[PERSISTENT] NTERSI on cd.[date]= NTERSI.[date]
inner join [dbo].[JKCEMENT] NTKCEM on cd.[date]= NTKCEM.[date]
inner join [dbo].[TRENT] NTRENT on cd.[date]= NTRENT.[date]
inner join [dbo].[TRIDENT] NTRIDE on cd.[date]= NTRIDE.[date]
inner join [dbo].[ASIANPAINT] NTSIAN on cd.[date]= NTSIAN.[date]
inner join [dbo].[STARCEMENT] NTTARC on cd.[date]= NTTARC.[date]
inner join [dbo].[CYIENT] NTYIEN on cd.[date]= NTYIEN.[date]
inner join [dbo].[SYMPHONY] NYYMPH on cd.[date]= NYYMPH.[date]
inner join [dbo].[IOB] OBOB on cd.[date]= OBOB.[date]
inner join [dbo].[VARROC] OCARRO on cd.[date]= OCARRO.[date]
inner join [dbo].[IOC] OCOC on cd.[date]= OCOC.[date]
inner join [dbo].[HERITGFOOD] ODERIT on cd.[date]= ODERIT.[date]
inner join [dbo].[JUBLFOOD] ODUBLF on cd.[date]= ODUBLF.[date]
inner join [dbo].[MAHLOG] OGAHLO on cd.[date]= OGAHLO.[date]
inner join [dbo].[VRLLOG] OGRLLO on cd.[date]= OGRLLO.[date]
inner join [dbo].[WHIRLPOOL] OLHIRL on cd.[date]= OLHIRL.[date]
inner join [dbo].[BAJAJCON] ONAJAJ on cd.[date]= ONAJAJ.[date]
inner join [dbo].[REDINGTON] ONEDIN on cd.[date]= ONEDIN.[date]
inner join [dbo].[BIOCON] ONIOCO on cd.[date]= ONIOCO.[date]
inner join [dbo].[DIXON] ONIXON on cd.[date]= ONIXON.[date]
inner join [dbo].[KNRCON] ONNRCO on cd.[date]= ONNRCO.[date]
inner join [dbo].[IRCON] ONRCON on cd.[date]= ONRCON.[date]
inner join [dbo].[CROMPTON] ONROMP on cd.[date]= ONROMP.[date]
inner join [dbo].[SUZLON] ONUZLO on cd.[date]= ONUZLO.[date]
inner join [dbo].[BAYERCROP] OPAYER on cd.[date]= OPAYER.[date]
inner join [dbo].[SHOPERSTOP] OPHOPE on cd.[date]= OPHOPE.[date]
inner join [dbo].[GODREJPROP] OPODRE on cd.[date]= OPODRE.[date]
inner join [dbo].[NAVINFLUOR] ORAVIN on cd.[date]= ORAVIN.[date]
--inner join [dbo].[CONCOR] ORONCO on cd.[date]= ORONCO.[date]
inner join [dbo].[TVSMOTOR] ORVSMO on cd.[date]= ORVSMO.[date]
inner join [dbo].[EICHERMOT] OTICHE on cd.[date]= OTICHE.[date]
inner join [dbo].[GREAVESCOT] OTREAV on cd.[date]= OTREAV.[date]
inner join [dbo].[NHPC] PCHPC on cd.[date]= PCHPC.[date]
inner join [dbo].[NTPC] PCTPC on cd.[date]= PCTPC.[date]
inner join [dbo].[FINPIPE] PEINPI on cd.[date]= PEINPI.[date]
inner join [dbo].[UPL] PLPL on cd.[date]= PLPL.[date]
inner join [dbo].[GPPL] PLPPL on cd.[date]= PLPPL.[date]
inner join [dbo].[MRPL] PLRPL on cd.[date]= PLRPL.[date]
inner join [dbo].[GSPL] PLSPL on cd.[date]= PLSPL.[date]
inner join [dbo].[BIRLACORPN] PNIRLA on cd.[date]= PNIRLA.[date]
inner join [dbo].[RAJESHEXPO] POAJES on cd.[date]= POAJES.[date]
inner join [dbo].[ICRA] RACRA on cd.[date]= RACRA.[date]
inner join [dbo].[CERA] RAERA on cd.[date]= RAERA.[date]
inner join [dbo].[GMRINFRA] RAMRIN on cd.[date]= RAMRIN.[date]
inner join [dbo].[PNCINFRA] RANCIN on cd.[date]= RANCIN.[date]
inner join [dbo].[SOLARA] RAOLAR on cd.[date]= RAOLAR.[date]
inner join [dbo].[PHILIPCARB] RBHILI on cd.[date]= RBHILI.[date]
inner join [dbo].[IRB] RBRB on cd.[date]= RBRB.[date]
inner join [dbo].[SPARC] RCPARC on cd.[date]= RCPARC.[date]
inner join [dbo].[SBICARD] RDBICA on cd.[date]= RDBICA.[date]
inner join [dbo].[VGUARD] RDGUAR on cd.[date]= RDGUAR.[date]
inner join [dbo].[THYROCARE] REHYRO on cd.[date]= REHYRO.[date]
inner join [dbo].[GICRE] REICRE on cd.[date]= REICRE.[date]
inner join [dbo].[JKTYRE] REKTYR on cd.[date]= REKTYR.[date]
inner join [dbo].[APOLLOTYRE] REPOLL on cd.[date]= REPOLL.[date]
inner join [dbo].[GALAXYSURF] RFALAX on cd.[date]= RFALAX.[date]
inner join [dbo].[MRF] RFRFdg on cd.[date]= RFRFdg.[date]
inner join [dbo].[SRF] RFRFh on cd.[date]= RFRFh.[date]
inner join [dbo].[HEIDELBERG] RGEIDE on cd.[date]= RGEIDE.[date]
inner join [dbo].[BHARATFORG] RGHARA on cd.[date]= RGHARA.[date]
inner join [dbo].[FINEORG] RGINEO on cd.[date]= RGINEO.[date]
inner join [dbo].[NAUKRI] RIAUKR on cd.[date]= RIAUKR.[date]
inner join [dbo].[GLENMARK] RKLENM on cd.[date]= RKLENM.[date]
inner join [dbo].[ABFRL] RLBFRL on cd.[date]= RLBFRL.[date]
inner join [dbo].[NATCOPHARM] RMATCO on cd.[date]= RMATCO.[date]
inner join [dbo].[JBCHEPHARM] RMBCHE on cd.[date]= RMBCHE.[date]
inner join [dbo].[AJANTPHARM] RMJANT on cd.[date]= RMJANT.[date]
inner join [dbo].[TORNTPHARM] RMORNT on cd.[date]= RMORNT.[date]
inner join [dbo].[CHENNPETRO] ROHENN on cd.[date]= ROHENN.[date]
inner join [dbo].[HINDPETRO] ROINDP on cd.[date]= ROINDP.[date]
inner join [dbo].[WIPRO] ROIPRO on cd.[date]= ROIPRO.[date]
inner join [dbo].[GODREJAGRO] ROODRE on cd.[date]= ROODRE.[date]
inner join [dbo].[SUPPETRO] ROUPPE on cd.[date]= ROUPPE.[date]
inner join [dbo].[DBCORP] RPBCOR on cd.[date]= RPBCOR.[date]
inner join [dbo].[WELCORP] RPELCO on cd.[date]= RPELCO.[date]
inner join [dbo].[DELTACORP] RPELTA on cd.[date]= RPELTA.[date]
inner join [dbo].[MINDACORP] RPINDA on cd.[date]= RPINDA.[date]
inner join [dbo].[TATAMOTORS] RSATAM on cd.[date]= RSATAM.[date]
inner join [dbo].[CHAMBLFERT] RTHAMB on cd.[date]= RTHAMB.[date]
inner join [dbo].[BLUEDART] RTLUED on cd.[date]= RTLUED.[date]
inner join [dbo].[VMART] RTMARTg on cd.[date]= RTMARTg.[date]
inner join [dbo].[DMART] RTMARTga on cd.[date]= RTMARTga.[date]
inner join [dbo].[INDIAMART] RTNDIA on cd.[date]= RTNDIA.[date]
inner join [dbo].[ECLERX] RXCLER on cd.[date]= RXCLER.[date]
inner join [dbo].[EIDPARRY] RYIDPA on cd.[date]= RYIDPA.[date]
inner join [dbo].[KSB] SBSB on cd.[date]= SBSB.[date]
inner join [dbo].[CESC] SCESC on cd.[date]= SCESC.[date]
inner join [dbo].[TEAMLEASE] SEEAML on cd.[date]= SEEAML.[date]
inner join [dbo].[GRSE] SERSE on cd.[date]= SERSE.[date]
inner join [dbo].[BSE] SESE on cd.[date]= SESE.[date]
inner join [dbo].[BASF] SFASF on cd.[date]= SFASF.[date]
inner join [dbo].[TATAELXSI] SIATAE on cd.[date]= SIATAE.[date]
inner join [dbo].[TATASTLBSL] SLATAS on cd.[date]= SLATAS.[date]
inner join [dbo].[CDSL] SLDSL on cd.[date]= SLDSL.[date]
inner join [dbo].[MFSL] SLFSL on cd.[date]= SLFSL.[date]
inner join [dbo].[PRSMJOHNSN] SNRSMJ on cd.[date]= SNRSMJ.[date]
inner join [dbo].[APOLLOHOSP] SPPOLL on cd.[date]= SPPOLL.[date]
inner join [dbo].[EDELWEISS] SSDELW on cd.[date]= SSDELW.[date]
inner join [dbo].[OFSS] SSFSS on cd.[date]= SSFSS.[date]
inner join [dbo].[QUESS] SSUESS on cd.[date]= SSUESS.[date]
inner join [dbo].[TATAINVEST] STATAI on cd.[date]= STATAI.[date]
inner join [dbo].[IBREALEST] STBREA on cd.[date]= STBREA.[date]
inner join [dbo].[SUNDRMFAST] STUNDR on cd.[date]= STUNDR.[date]
inner join [dbo].[TV18BRDCST] STV18B on cd.[date]= STV18B.[date]
inner join [dbo].[BAJAJFINSV] SVAJAJ on cd.[date]= SVAJAJ.[date]
inner join [dbo].[IDFCFIRSTB] TBDFCF on cd.[date]= TBDFCF.[date]
inner join [dbo].[BBTC] TCBTC on cd.[date]= TCBTC.[date]
inner join [dbo].[MMTC] TCMTC on cd.[date]= TCMTC.[date]
inner join [dbo].[IRCTC] TCRCTC on cd.[date]= TCRCTC.[date]
inner join [dbo].[JAICORPLTD] TDAICO on cd.[date]= TDAICO.[date]
inner join [dbo].[CEATLTD] TDEATL on cd.[date]= TDEATL.[date]
inner join [dbo].[RECLTD] TDECLT on cd.[date]= TDECLT.[date]
inner join [dbo].[PHOENIXLTD] TDHOEN on cd.[date]= TDHOEN.[date]
inner join [dbo].[ALEMBICLTD] TDLEMB on cd.[date]= TDLEMB.[date]
inner join [dbo].[EMAMILTD] TDMAMI on cd.[date]= TDMAMI.[date]
inner join [dbo].[GMDCLTD] TDMDCL on cd.[date]= TDMDCL.[date]
inner join [dbo].[BOSCHLTD] TDOSCH on cd.[date]= TDOSCH.[date]
inner join [dbo].[APLLTD] TDPLLT on cd.[date]= TDPLLT.[date]
inner join [dbo].[GUJGASLTD] TDUJGA on cd.[date]= TDUJGA.[date]
inner join [dbo].[TASTYBITE] TEASTY on cd.[date]= TEASTY.[date]
inner join [dbo].[GILLETTE] TEILLE on cd.[date]= TEILLE.[date]
inner join [dbo].[GRAPHITE] TERAPH on cd.[date]= TERAPH.[date]
inner join [dbo].[MARUTI] TIARUT on cd.[date]= TIARUT.[date]
inner join [dbo].[BHARTIARTL] TLHART on cd.[date]= TLHART.[date]
inner join [dbo].[VTL] TLTL on cd.[date]= TLTL.[date]
inner join [dbo].[BAJAJ-AUTO] TOAJAJ on cd.[date]= TOAJAJ.[date]
inner join [dbo].[JAMNAAUTO] TOAMNA on cd.[date]= TOAMNA.[date]
inner join [dbo].[DEEPAKNTR] TREEPA on cd.[date]= TREEPA.[date]
inner join [dbo].[ADANIPORTS] TSDANI on cd.[date]= TSDANI.[date]
inner join [dbo].[ESCORTS] TSSCOR on cd.[date]= TSSCOR.[date]
inner join [dbo].[LTTS] TSTTS on cd.[date]= TSTTS.[date]
inner join [dbo].[DISHTV] TVISHT on cd.[date]= TVISHT.[date]
inner join [dbo].[SUNTV] TVUNTV on cd.[date]= TVUNTV.[date]
inner join [dbo].[SONATSOFTW] TWONAT on cd.[date]= TWONAT.[date]
inner join [dbo].[OBEROIRLTY] TYBERO on cd.[date]= TYBERO.[date]
inner join [dbo].[CUB] UBUB on cd.[date]= UBUB.[date]
inner join [dbo].[GULFOILLUB] UBULFO on cd.[date]= UBULFO.[date]
inner join [dbo].[NAVNETEDUL] ULAVNE on cd.[date]= ULAVNE.[date]
inner join [dbo].[ATUL] ULTUL on cd.[date]= ULTUL.[date]
inner join [dbo].[TATACONSUM] UMATAC on cd.[date]= UMATAC.[date]
inner join [dbo].[NATIONALUM] UMATIO on cd.[date]= UMATIO.[date]
inner join [dbo].[HATSUN] UNATSU on cd.[date]= UNATSU.[date]
inner join [dbo].[DABUR] URABUR on cd.[date]= URABUR.[date]
inner join [dbo].[INOXLEISUR] URNOXL on cd.[date]= URNOXL.[date]
inner join [dbo].[HONAUT] UTONAU on cd.[date]= UTONAU.[date]
inner join [dbo].[SJVN] VNJVN on cd.[date]= VNJVN.[date]
inner join [dbo].[TATAMTRDVR] VRATAM on cd.[date]= VRATAM.[date]
inner join [dbo].[HINDUNILVR] VRINDU on cd.[date]= VRINDU.[date]
inner join [dbo].[PVR] VRVR on cd.[date]= VRVR.[date]
inner join [dbo].[BLISSGVS] VSLISS on cd.[date]= VSLISS.[date]
inner join [dbo].[KALPATPOWR] WRALPA on cd.[date]= WRALPA.[date]
inner join [dbo].[OMAXE] XEMAXE on cd.[date]= XEMAXE.[date]
inner join [dbo].[RELAXO] XOELAX on cd.[date]= XOELAX.[date]
inner join [dbo].[GLAXO] XOLAXO on cd.[date]= XOLAXO.[date]
inner join [dbo].[TCIEXP] XPCIEX on cd.[date]= XPCIEX.[date]
inner join [dbo].[KARURVYSYA] YAARUR on cd.[date]= YAARUR.[date]
inner join [dbo].[VENKEYS] YSENKE on cd.[date]= YSENKE.[date]
