# sam_df <- sqlQuery(conn, "SELECT *, [open]-[high]  as [open-high], [open]-[low]  as [open-low], 
# [open]-[low] - LAG([open]-[low]) OVER(ORDER BY [date]) as openlow
# from [dbo].[ASTRAL]
# order by [date] desc")
# 
# sam_df =  sam_df %>% distinct(date, .keep_all=TRUE)
# 
# library(ggplot2)
# p <- ggplot(sam_df[c(1:100),c(2,17,18)], aes(x=date, y=openlow)) +
#   geom_line( color="#69b3a2") + 
#   xlab("") +
#   theme(axis.text.x=element_text(angle=60, hjust=1)) 
# 
# p <- ggplot(sam_df_All[c(19000:),c(1,2,18)], aes(x=date, y=openlow)) +
#   geom_line(aes(colour = ticker)) + 
#   xlab("") +
#   theme(axis.text.x=element_text(angle=60, hjust=1))
# ggplotly(p)


#17940:18035


update_top_hundred_tables <- function() {
sqlQuery(conn, "SELECT *, [open]-[high]  as [open-high], [open]-[low]  as [open-low], 
[open]-[low] - LAG([open]-[low]) OVER (
		PARTITION BY ticker 
		ORDER BY [date])  as openlow
from
(select * from (select top 100 * from [dbo].[3MINDIA] order by [date] desc ) table138 union 
select * from (select top 100 * from [dbo].[AARTIDRUGS] order by [date] desc ) table232 union 
select * from (select top 100 * from [dbo].[AARTIIND] order by [date] desc ) table212 union 
select * from (select top 100 * from [dbo].[AAVAS] order by [date] desc ) table477 union 
select * from (select top 100 * from [dbo].[ABB] order by [date] desc ) table132 union 
select * from (select top 100 * from [dbo].[ABB_copy] order by [date] desc ) table183 union 
select * from (select top 100 * from [dbo].[ABBOTINDIA] order by [date] desc ) table334 union 
select * from (select top 100 * from [dbo].[ABCAPITAL] order by [date] desc ) table444 union 
select * from (select top 100 * from [dbo].[ABFRL] order by [date] desc ) table394 union 
select * from (select top 100 * from [dbo].[ACC] order by [date] desc ) table197 union 
select * from (select top 100 * from [dbo].[ADANIENT] order by [date] desc ) table198 union 
select * from (select top 100 * from [dbo].[ADANIGREEN] order by [date] desc ) table469 union 
select * from (select top 100 * from [dbo].[ADANIPORTS] order by [date] desc ) table319 union 
select * from (select top 100 * from [dbo].[ADANITRANS] order by [date] desc ) table401 union 
select * from (select top 100 * from [dbo].[ADVENZYMES] order by [date] desc ) table420 union 
select * from (select top 100 * from [dbo].[AEGISCHEM] order by [date] desc ) table217 union 
select * from (select top 100 * from [dbo].[AFFLE] order by [date] desc ) table488 union 
select * from (select top 100 * from [dbo].[AIAENG] order by [date] desc ) table263 union 
select * from (select top 100 * from [dbo].[AJANTPHARM] order by [date] desc ) table196 union 
select * from (select top 100 * from [dbo].[AKZOINDIA] order by [date] desc ) table195 union 
select * from (select top 100 * from [dbo].[ALEMBICLTD] order by [date] desc ) table175 union 
select * from (select top 100 * from [dbo].[ALKEM] order by [date] desc ) table408 union 
select * from (select top 100 * from [dbo].[ALKYLAMINE] order by [date] desc ) table321 union 
select * from (select top 100 * from [dbo].[ALOKINDS] order by [date] desc ) table438 union 
select * from (select top 100 * from [dbo].[AMARAJABAT] order by [date] desc ) table182 union 
select * from (select top 100 * from [dbo].[AMBER] order by [date] desc ) table458 union 
select * from (select top 100 * from [dbo].[AMBUJACEM] order by [date] desc ) table164 union 
select * from (select top 100 * from [dbo].[APLAPOLLO] order by [date] desc ) table379 union 
select * from (select top 100 * from [dbo].[APLLTD] order by [date] desc ) table376 union 
select * from (select top 100 * from [dbo].[APOLLOHOSP] order by [date] desc ) table181 union 
select * from (select top 100 * from [dbo].[APOLLOTYRE] order by [date] desc ) table66 union 
select * from (select top 100 * from [dbo].[ASHOKA] order by [date] desc ) table361 union 
select * from (select top 100 * from [dbo].[ASHOKLEY] order by [date] desc ) table179 union 
select * from (select top 100 * from [dbo].[ASIANPAINT] order by [date] desc ) table180 union 
select * from (select top 100 * from [dbo].[ASTERDM] order by [date] desc ) table461 union 
select * from (select top 100 * from [dbo].[ASTRAL] order by [date] desc ) table302 union 
select * from (select top 100 * from [dbo].[ASTRAZEN] order by [date] desc ) table222 union 
select * from (select top 100 * from [dbo].[ATUL] order by [date] desc ) table207 union 
select * from (select top 100 * from [dbo].[AUBANK] order by [date] desc ) table442 union 
select * from (select top 100 * from [dbo].[AUROPHARMA] order by [date] desc ) table45 union 
select * from (select top 100 * from [dbo].[AVANTIFEED] order by [date] desc ) table375 union 
select * from (select top 100 * from [dbo].[AXISBANK] order by [date] desc ) table54 union 
select * from (select top 100 * from [dbo].[BAJAJ-AUTO] order by [date] desc ) table107 union 
select * from (select top 100 * from [dbo].[BAJAJCON] order by [date] desc ) table387 union 
select * from (select top 100 * from [dbo].[BAJAJELEC] order by [date] desc ) table318 union 
select * from (select top 100 * from [dbo].[BAJAJFINSV] order by [date] desc ) table335 union 
select * from (select top 100 * from [dbo].[BAJAJHLDNG] order by [date] desc ) table221 union 
select * from (select top 100 * from [dbo].[BAJFINANCE] order by [date] desc ) table206 union 
select * from (select top 100 * from [dbo].[BALKRISIND] order by [date] desc ) table265 union 
select * from (select top 100 * from [dbo].[BALMLAWRIE] order by [date] desc ) table185 union 
select * from (select top 100 * from [dbo].[BALRAMCHIN] order by [date] desc ) table184 union 
select * from (select top 100 * from [dbo].[BANDHANBNK] order by [date] desc ) table464 union 
select * from (select top 100 * from [dbo].[BANKBARODA] order by [date] desc ) table187 union 
select * from (select top 100 * from [dbo].[BANKINDIA] order by [date] desc ) table186 union 
select * from (select top 100 * from [dbo].[BASF] order by [date] desc ) table188 union 
select * from (select top 100 * from [dbo].[BATAINDIA] order by [date] desc ) table189 union 
select * from (select top 100 * from [dbo].[BAYERCROP] order by [date] desc ) table352 union 
select * from (select top 100 * from [dbo].[BBTC] order by [date] desc ) table225 union 
select * from (select top 100 * from [dbo].[BDL] order by [date] desc ) table463 union 
select * from (select top 100 * from [dbo].[BEL] order by [date] desc ) table194 union 
select * from (select top 100 * from [dbo].[BEML] order by [date] desc ) table193 union 
select * from (select top 100 * from [dbo].[BERGEPAINT] order by [date] desc ) table192 union 
select * from (select top 100 * from [dbo].[BHARATFORG] order by [date] desc ) table48 union 
select * from (select top 100 * from [dbo].[BHARATRAS] order by [date] desc ) table223 union 
select * from (select top 100 * from [dbo].[BHARTIARTL] order by [date] desc ) table177 union 
select * from (select top 100 * from [dbo].[BHEL] order by [date] desc ) table50 union 
select * from (select top 100 * from [dbo].[BIOCON] order by [date] desc ) table244 union 
select * from (select top 100 * from [dbo].[BIRLACORPN] order by [date] desc ) table191 union 
select * from (select top 100 * from [dbo].[BLISSGVS] order by [date] desc ) table358 union 
select * from (select top 100 * from [dbo].[BLUEDART] order by [date] desc ) table190 union 
select * from (select top 100 * from [dbo].[BLUESTARCO] order by [date] desc ) table178 union 
select * from (select top 100 * from [dbo].[BOMDYEING] order by [date] desc ) table49 union 
select * from (select top 100 * from [dbo].[BOSCHLTD] order by [date] desc ) table213 union 
select * from (select top 100 * from [dbo].[BPCL] order by [date] desc ) table47 union 
select * from (select top 100 * from [dbo].[BRIGADE] order by [date] desc ) table325 union 
select * from (select top 100 * from [dbo].[BRITANNIA] order by [date] desc ) table51 union 
select * from (select top 100 * from [dbo].[BSE] order by [date] desc ) table432 union 
select * from (select top 100 * from [dbo].[BSOFT] order by [date] desc ) table200 union 
select * from (select top 100 * from [dbo].[CADILAHC] order by [date] desc ) table131 union 
select * from (select top 100 * from [dbo].[CANBK] order by [date] desc ) table224 union 
select * from (select top 100 * from [dbo].[CANFINHOME] order by [date] desc ) table157 union 
select * from (select top 100 * from [dbo].[CAPLIPOINT] order by [date] desc ) table397 union 
select * from (select top 100 * from [dbo].[CARBORUNIV] order by [date] desc ) table209 union 
select * from (select top 100 * from [dbo].[CARERATING] order by [date] desc ) table389 union 
select * from (select top 100 * from [dbo].[CASTROLIND] order by [date] desc ) table287 union 
select * from (select top 100 * from [dbo].[CCL] order by [date] desc ) table246 union 
select * from (select top 100 * from [dbo].[CDSL] order by [date] desc ) table441 union 
select * from (select top 100 * from [dbo].[CEATLTD] order by [date] desc ) table326 union 
select * from (select top 100 * from [dbo].[CENTRALBK] order by [date] desc ) table311 union 
select * from (select top 100 * from [dbo].[CENTURYPLY] order by [date] desc ) table272 union 
select * from (select top 100 * from [dbo].[CENTURYTEX] order by [date] desc ) table52 union 
select * from (select top 100 * from [dbo].[CERA] order by [date] desc ) table317 union 
select * from (select top 100 * from [dbo].[CESC] order by [date] desc ) table199 union 
select * from (select top 100 * from [dbo].[CGCL] order by [date] desc ) table364 union 
select * from (select top 100 * from [dbo].[CHALET] order by [date] desc ) table483 union 
select * from (select top 100 * from [dbo].[CHAMBLFERT] order by [date] desc ) table173 union 
select * from (select top 100 * from [dbo].[CHENNPETRO] order by [date] desc ) table202 union 
select * from (select top 100 * from [dbo].[CHOLAFIN] order by [date] desc ) table201 union 
select * from (select top 100 * from [dbo].[CHOLAHLDNG] order by [date] desc ) table203 union 
select * from (select top 100 * from [dbo].[CIPLA] order by [date] desc ) table46 union 
select * from (select top 100 * from [dbo].[COALINDIA] order by [date] desc ) table366 union 
select * from (select top 100 * from [dbo].[CREDITACC] order by [date] desc ) table476 union 
select * from (select top 100 * from [dbo].[CRISIL] order by [date] desc ) table130 union 
select * from (select top 100 * from [dbo].[CROMPTON] order by [date] desc ) table416 union 
select * from (select top 100 * from [dbo].[CSBBANK] order by [date] desc ) table495 union 
select * from (select top 100 * from [dbo].[CUB] order by [date] desc ) table208 union 
select * from (select top 100 * from [dbo].[CUMMINSIND] order by [date] desc ) table103 union 
select * from (select top 100 * from [dbo].[CYIENT] order by [date] desc ) table278 union 
select * from (select top 100 * from [dbo].[DABUR] order by [date] desc ) table104 union 
select * from (select top 100 * from [dbo].[DALBHARAT] order by [date] desc ) table481 union 
select * from (select top 100 * from [dbo].[DBCORP] order by [date] desc ) table349 union 
select * from (select top 100 * from [dbo].[DBL] order by [date] desc ) table421 union 
select * from (select top 100 * from [dbo].[DCAL] order by [date] desc ) table243 union 
select * from (select top 100 * from [dbo].[DCBBANK] order by [date] desc ) table284 union 
select * from (select top 100 * from [dbo].[DCMSHRIRAM] order by [date] desc ) table98 union 
select * from (select top 100 * from [dbo].[DEEPAKNTR] order by [date] desc ) table360 union 
select * from (select top 100 * from [dbo].[DELTACORP] order by [date] desc ) table316 union 
select * from (select top 100 * from [dbo].[DHANUKA] order by [date] desc ) table373 union 
select * from (select top 100 * from [dbo].[DISHTV] order by [date] desc ) table303 union 
select * from (select top 100 * from [dbo].[DIVISLAB] order by [date] desc ) table227 union 
select * from (select top 100 * from [dbo].[DIXON] order by [date] desc ) table445 union 
select * from (select top 100 * from [dbo].[DLF] order by [date] desc ) table308 union 
select * from (select top 100 * from [dbo].[DMART] order by [date] desc ) table433 union 
select * from (select top 100 * from [dbo].[DRREDDY] order by [date] desc ) table15 union 
select * from (select top 100 * from [dbo].[ECLERX] order by [date] desc ) table324 union 
select * from (select top 100 * from [dbo].[EDELWEISS] order by [date] desc ) table320 union 
select * from (select top 100 * from [dbo].[EICHERMOT] order by [date] desc ) table16 union 
select * from (select top 100 * from [dbo].[EIDPARRY] order by [date] desc ) table73 union 
select * from (select top 100 * from [dbo].[EIHOTEL] order by [date] desc ) table2 union 
select * from (select top 100 * from [dbo].[ELGIEQUIP] order by [date] desc ) table96 union 
select * from (select top 100 * from [dbo].[EMAMILTD] order by [date] desc ) table279 union 
select * from (select top 100 * from [dbo].[ENDURANCE] order by [date] desc ) table426 union 
select * from (select top 100 * from [dbo].[ENGINERSIN] order by [date] desc ) table14 union 
select * from (select top 100 * from [dbo].[EQUITAS] order by [date] desc ) table413 union 
select * from (select top 100 * from [dbo].[ERIS] order by [date] desc ) table440 union 
select * from (select top 100 * from [dbo].[ESABINDIA] order by [date] desc ) table94 union 
select * from (select top 100 * from [dbo].[ESCORTS] order by [date] desc ) table13 union 
select * from (select top 100 * from [dbo].[EXIDEIND] order by [date] desc ) table75 union 
select * from (select top 100 * from [dbo].[FCONSUMER] order by [date] desc ) table377 union 
select * from (select top 100 * from [dbo].[FDC] order by [date] desc ) table78 union 
select * from (select top 100 * from [dbo].[FEDERALBNK] order by [date] desc ) table5 union 
select * from (select top 100 * from [dbo].[FINCABLES] order by [date] desc ) table74 union 
select * from (select top 100 * from [dbo].[FINEORG] order by [date] desc ) table470 union 
select * from (select top 100 * from [dbo].[FINPIPE] order by [date] desc ) table82 union 
select * from (select top 100 * from [dbo].[FLUOROCHEM] order by [date] desc ) table493 union 
select * from (select top 100 * from [dbo].[FORTIS] order by [date] desc ) table306 union 
select * from (select top 100 * from [dbo].[FRETAIL] order by [date] desc ) table422 union 
select * from (select top 100 * from [dbo].[FSL] order by [date] desc ) table293 union 
select * from (select top 100 * from [dbo].[GAEL] order by [date] desc ) table67 union 
select * from (select top 100 * from [dbo].[GAIL] order by [date] desc ) table8 union 
select * from (select top 100 * from [dbo].[GALAXYSURF] order by [date] desc ) table459 union 
select * from (select top 100 * from [dbo].[GARFIBRES] order by [date] desc ) table140 union 
select * from (select top 100 * from [dbo].[GEPIL] order by [date] desc ) table83 union 
select * from (select top 100 * from [dbo].[GESHIP] order by [date] desc ) table68 union 
select * from (select top 100 * from [dbo].[GHCL] order by [date] desc ) table9 union 
select * from (select top 100 * from [dbo].[GICRE] order by [date] desc ) table450 union 
select * from (select top 100 * from [dbo].[GILLETTE] order by [date] desc ) table85 union 
select * from (select top 100 * from [dbo].[GLAXO] order by [date] desc ) table84 union 
select * from (select top 100 * from [dbo].[GLENMARK] order by [date] desc ) table69 union 
select * from (select top 100 * from [dbo].[GMDCLTD] order by [date] desc ) table70 union 
select * from (select top 100 * from [dbo].[GMMPFAUDLR] order by [date] desc ) table460 union 
select * from (select top 100 * from [dbo].[GMRINFRA] order by [date] desc ) table280 union 
select * from (select top 100 * from [dbo].[GNFC] order by [date] desc ) table87 union 
select * from (select top 100 * from [dbo].[GODFRYPHLP] order by [date] desc ) table10 union 
select * from (select top 100 * from [dbo].[GODREJAGRO] order by [date] desc ) table448 union 
select * from (select top 100 * from [dbo].[GODREJCP] order by [date] desc ) table71 union 
select * from (select top 100 * from [dbo].[GODREJIND] order by [date] desc ) table72 union 
select * from (select top 100 * from [dbo].[GODREJPROP] order by [date] desc ) table347 union 
select * from (select top 100 * from [dbo].[GPPL] order by [date] desc ) table359 union 
select * from (select top 100 * from [dbo].[GRANULES] order by [date] desc ) table257 union 
select * from (select top 100 * from [dbo].[GRAPHITE] order by [date] desc ) table79 union 
select * from (select top 100 * from [dbo].[GRASIM] order by [date] desc ) table86 union 
select * from (select top 100 * from [dbo].[GREAVESCOT] order by [date] desc ) table139 union 
select * from (select top 100 * from [dbo].[GRINDWELL] order by [date] desc ) table282 union 
select * from (select top 100 * from [dbo].[GRSE] order by [date] desc ) table479 union 
select * from (select top 100 * from [dbo].[GSFC] order by [date] desc ) table12 union 
select * from (select top 100 * from [dbo].[GSPL] order by [date] desc ) table266 union 
select * from (select top 100 * from [dbo].[GUJALKALI] order by [date] desc ) table89 union 
select * from (select top 100 * from [dbo].[GUJGASLTD] order by [date] desc ) table403 union 
select * from (select top 100 * from [dbo].[GULFOILLUB] order by [date] desc ) table398 union 
select * from (select top 100 * from [dbo].[HAL] order by [date] desc ) table462 union 
select * from (select top 100 * from [dbo].[HATHWAY] order by [date] desc ) table354 union 
select * from (select top 100 * from [dbo].[HATSUN] order by [date] desc ) table396 union 
select * from (select top 100 * from [dbo].[HAVELLS] order by [date] desc ) table482 union 
select * from (select top 100 * from [dbo].[HCLTECH] order by [date] desc ) table136 union 
select * from (select top 100 * from [dbo].[HDFC] order by [date] desc ) table76 union 
select * from (select top 100 * from [dbo].[HDFCAMC] order by [date] desc ) table475 union 
select * from (select top 100 * from [dbo].[HDFCBANK] order by [date] desc ) table3 union 
select * from (select top 100 * from [dbo].[HDFCLIFE] order by [date] desc ) table456 union 
select * from (select top 100 * from [dbo].[HEG] order by [date] desc ) table90 union 
select * from (select top 100 * from [dbo].[HEIDELBERG] order by [date] desc ) table11 union 
select * from (select top 100 * from [dbo].[HERITGFOOD] order by [date] desc ) table92 union 
select * from (select top 100 * from [dbo].[HEROMOTOCO] order by [date] desc ) table91 union 
select * from (select top 100 * from [dbo].[HFCL] order by [date] desc ) table172 union 
select * from (select top 100 * from [dbo].[HINDALCO] order by [date] desc ) table4 union 
select * from (select top 100 * from [dbo].[HINDCOPPER] order by [date] desc ) table350 union 
select * from (select top 100 * from [dbo].[HINDPETRO] order by [date] desc ) table23 union 
select * from (select top 100 * from [dbo].[HINDUNILVR] order by [date] desc ) table6 union 
select * from (select top 100 * from [dbo].[HINDZINC] order by [date] desc ) table141 union 
select * from (select top 100 * from [dbo].[HONAUT] order by [date] desc ) table81 union 
select * from (select top 100 * from [dbo].[HSCL] order by [date] desc ) table297 union 
select * from (select top 100 * from [dbo].[HUDCO] order by [date] desc ) table435 union 
select * from (select top 100 * from [dbo].[IBREALEST] order by [date] desc ) table250 union 
select * from (select top 100 * from [dbo].[IBULHSGFIN] order by [date] desc ) table395 union 
select * from (select top 100 * from [dbo].[ICICIBANK] order by [date] desc ) table146 union 
select * from (select top 100 * from [dbo].[ICICIGI] order by [date] desc ) table446 union 
select * from (select top 100 * from [dbo].[ICICIPRULI] order by [date] desc ) table425 union 
select * from (select top 100 * from [dbo].[ICRA] order by [date] desc ) table304 union 
select * from (select top 100 * from [dbo].[IDBI] order by [date] desc ) table33 union 
select * from (select top 100 * from [dbo].[IDEA] order by [date] desc ) table299 union 
select * from (select top 100 * from [dbo].[IDFC] order by [date] desc ) table261 union 
select * from (select top 100 * from [dbo].[IDFCFIRSTB] order by [date] desc ) table404 union 
select * from (select top 100 * from [dbo].[IEX] order by [date] desc ) table451 union 
select * from (select top 100 * from [dbo].[IFBIND] order by [date] desc ) table101 union 
select * from (select top 100 * from [dbo].[IGL] order by [date] desc ) table237 union 
select * from (select top 100 * from [dbo].[IIFL] order by [date] desc ) table255 union 
select * from (select top 100 * from [dbo].[IIFLWAM] order by [date] desc ) table492 union 
select * from (select top 100 * from [dbo].[INDHOTEL] order by [date] desc ) table80 union 
select * from (select top 100 * from [dbo].[INDIACEM] order by [date] desc ) table22 union 
select * from (select top 100 * from [dbo].[INDIAMART] order by [date] desc ) table487 union 
select * from (select top 100 * from [dbo].[INDIANB] order by [date] desc ) table296 union 
select * from (select top 100 * from [dbo].[INDIGO] order by [date] desc ) table405 union 
select * from (select top 100 * from [dbo].[INDOCO] order by [date] desc ) table252 union 
select * from (select top 100 * from [dbo].[INDUSINDBK] order by [date] desc ) table105 union 
select * from (select top 100 * from [dbo].[INDUSTOWER] order by [date] desc ) table388 union 
select * from (select top 100 * from [dbo].[INFRATEL] order by [date] desc ) table390 union 
select * from (select top 100 * from [dbo].[INFY] order by [date] desc ) table17 union 
select * from (select top 100 * from [dbo].[INGERRAND] order by [date] desc ) table116 union 
select * from (select top 100 * from [dbo].[INOXLEISUR] order by [date] desc ) table268 union 
select * from (select top 100 * from [dbo].[IOB] order by [date] desc ) table115 union 
select * from (select top 100 * from [dbo].[IOC] order by [date] desc ) table31 union 
select * from (select top 100 * from [dbo].[IOLCP] order by [date] desc ) table365 union 
select * from (select top 100 * from [dbo].[IPCALAB] order by [date] desc ) table29 union 
select * from (select top 100 * from [dbo].[IRB] order by [date] desc ) table328 union 
select * from (select top 100 * from [dbo].[IRCON] order by [date] desc ) table478 union 
select * from (select top 100 * from [dbo].[IRCTC] order by [date] desc ) table494 union 
select * from (select top 100 * from [dbo].[ISEC] order by [date] desc ) table466 union 
select * from (select top 100 * from [dbo].[ITC] order by [date] desc ) table30 union 
select * from (select top 100 * from [dbo].[ITI] order by [date] desc ) table125 union 
select * from (select top 100 * from [dbo].[J&KBANK] order by [date] desc ) table204 union 
select * from (select top 100 * from [dbo].[JAGRAN] order by [date] desc ) table267 union 
select * from (select top 100 * from [dbo].[JAICORPLTD] order by [date] desc ) table99 union 
select * from (select top 100 * from [dbo].[JAMNAAUTO] order by [date] desc ) table367 union 
select * from (select top 100 * from [dbo].[JBCHEPHARM] order by [date] desc ) table120 union 
select * from (select top 100 * from [dbo].[JCHAC] order by [date] desc ) table118 union 
select * from (select top 100 * from [dbo].[JINDALSAW] order by [date] desc ) table119 union 
select * from (select top 100 * from [dbo].[JINDALSTEL] order by [date] desc ) table19 union 
select * from (select top 100 * from [dbo].[JKCEMENT] order by [date] desc ) table269 union 
select * from (select top 100 * from [dbo].[JKLAKSHMI] order by [date] desc ) table277 union 
select * from (select top 100 * from [dbo].[JKPAPER] order by [date] desc ) table258 union 
select * from (select top 100 * from [dbo].[JKTYRE] order by [date] desc ) table245 union 
select * from (select top 100 * from [dbo].[JMFINANCIL] order by [date] desc ) table283 union 
select * from (select top 100 * from [dbo].[JSL] order by [date] desc ) table235 union 
select * from (select top 100 * from [dbo].[JSLHISAR] order by [date] desc ) table410 union 
select * from (select top 100 * from [dbo].[JSWENERGY] order by [date] desc ) table348 union 
select * from (select top 100 * from [dbo].[JSWSTEEL] order by [date] desc ) table228 union 
select * from (select top 100 * from [dbo].[JTEKTINDIA] order by [date] desc ) table238 union 
select * from (select top 100 * from [dbo].[JUBLFOOD] order by [date] desc ) table353 union 
select * from (select top 100 * from [dbo].[JUSTDIAL] order by [date] desc ) table392 union 
select * from (select top 100 * from [dbo].[JYOTHYLAB] order by [date] desc ) table323 union 
select * from (select top 100 * from [dbo].[KAJARIACER] order by [date] desc ) table127 union 
select * from (select top 100 * from [dbo].[KALPATPOWR] order by [date] desc ) table102 union 
select * from (select top 100 * from [dbo].[KANSAINER] order by [date] desc ) table128 union 
select * from (select top 100 * from [dbo].[KARURVYSYA] order by [date] desc ) table28 union 
select * from (select top 100 * from [dbo].[KEC] order by [date] desc ) table205 union 
select * from (select top 100 * from [dbo].[KEI] order by [date] desc ) table271 union 
select * from (select top 100 * from [dbo].[KNRCON] order by [date] desc ) table327 union 
select * from (select top 100 * from [dbo].[KOLTEPATIL] order by [date] desc ) table322 union 
select * from (select top 100 * from [dbo].[KOTAKBANK] order by [date] desc ) table61 union 
select * from (select top 100 * from [dbo].[KRBL] order by [date] desc ) table65 union 
select * from (select top 100 * from [dbo].[KSB] order by [date] desc ) table126 union 
select * from (select top 100 * from [dbo].[KSCL] order by [date] desc ) table314 union 
select * from (select top 100 * from [dbo].[KTKBANK] order by [date] desc ) table55 union 
select * from (select top 100 * from [dbo].[L&TFH] order by [date] desc ) table374 union 
select * from (select top 100 * from [dbo].[LALPATHLAB] order by [date] desc ) table407 union 
select * from (select top 100 * from [dbo].[LAOPALA] order by [date] desc ) table301 union 
select * from (select top 100 * from [dbo].[LAURUSLABS] order by [date] desc ) table431 union 
select * from (select top 100 * from [dbo].[LAXMIMACH] order by [date] desc ) table97 union 
select * from (select top 100 * from [dbo].[LEMONTREE] order by [date] desc ) table467 union 
select * from (select top 100 * from [dbo].[LICHSGFIN] order by [date] desc ) table129 union 
select * from (select top 100 * from [dbo].[LINDEINDIA] order by [date] desc ) table56 union 
select * from (select top 100 * from [dbo].[LT] order by [date] desc ) table95 union 
select * from (select top 100 * from [dbo].[LTI] order by [date] desc ) table419 union 
select * from (select top 100 * from [dbo].[LTTS] order by [date] desc ) table424 union 
select * from (select top 100 * from [dbo].[LUPIN] order by [date] desc ) table63 union 
select * from (select top 100 * from [dbo].[LUXIND] order by [date] desc ) table406 union 
select * from (select top 100 * from [dbo].[M&M] order by [date] desc ) table20 union 
select * from (select top 100 * from [dbo].[M&MFIN] order by [date] desc ) table270 union 
select * from (select top 100 * from [dbo].[MAHABANK] order by [date] desc ) table242 union 
select * from (select top 100 * from [dbo].[MAHINDCIE] order by [date] desc ) table312 union 
select * from (select top 100 * from [dbo].[MAHLOG] order by [date] desc ) table454 union 
select * from (select top 100 * from [dbo].[MAHSCOOTER] order by [date] desc ) table111 union 
select * from (select top 100 * from [dbo].[MAHSEAMLES] order by [date] desc ) table93 union 
select * from (select top 100 * from [dbo].[MANAPPURAM] order by [date] desc ) table357 union 
select * from (select top 100 * from [dbo].[MARICO] order by [date] desc ) table7 union 
select * from (select top 100 * from [dbo].[MARUTI] order by [date] desc ) table229 union 
select * from (select top 100 * from [dbo].[MASFIN] order by [date] desc ) table449 union 
select * from (select top 100 * from [dbo].[MCDOWELL-N] order by [date] desc ) table110 union 
select * from (select top 100 * from [dbo].[MCX] order by [date] desc ) table381 union 
select * from (select top 100 * from [dbo].[METROPOLIS] order by [date] desc ) table485 union 
select * from (select top 100 * from [dbo].[MFSL] order by [date] desc ) table24 union 
select * from (select top 100 * from [dbo].[MGL] order by [date] desc ) table417 union 
select * from (select top 100 * from [dbo].[MHRIL] order by [date] desc ) table340 union 
select * from (select top 100 * from [dbo].[MIDHANI] order by [date] desc ) table465 union 
select * from (select top 100 * from [dbo].[MINDACORP] order by [date] desc ) table382 union 
select * from (select top 100 * from [dbo].[MINDAIND] order by [date] desc ) table292 union 
select * from (select top 100 * from [dbo].[MINDTREE] order by [date] desc ) table298 union 
select * from (select top 100 * from [dbo].[MMTC] order by [date] desc ) table351 union 
select * from (select top 100 * from [dbo].[MOIL] order by [date] desc ) table368 union 
select * from (select top 100 * from [dbo].[MOTHERSUMI] order by [date] desc ) table106 union 
select * from (select top 100 * from [dbo].[MOTILALOFS] order by [date] desc ) table313 union 
select * from (select top 100 * from [dbo].[MPHASIS] order by [date] desc ) table108 union 
select * from (select top 100 * from [dbo].[MRF] order by [date] desc ) table109 union 
select * from (select top 100 * from [dbo].[MRPL] order by [date] desc ) table26 union 
select * from (select top 100 * from [dbo].[MUTHOOTFIN] order by [date] desc ) table369 union 
select * from (select top 100 * from [dbo].[NAM-INDIA] order by [date] desc ) table453 union 
select * from (select top 100 * from [dbo].[NATCOPHARM] order by [date] desc ) table21 union 
select * from (select top 100 * from [dbo].[NATIONALUM] order by [date] desc ) table25 union 
select * from (select top 100 * from [dbo].[NAUKRI] order by [date] desc ) table285 union 
select * from (select top 100 * from [dbo].[NAVINFLUOR] order by [date] desc ) table307 union 
select * from (select top 100 * from [dbo].[NAVNETEDUL] order by [date] desc ) table88 union 
select * from (select top 100 * from [dbo].[NBCC] order by [date] desc ) table384 union 
select * from (select top 100 * from [dbo].[NCC] order by [date] desc ) table176 union 
select * from (select top 100 * from [dbo].[NESCO] order by [date] desc ) table333 union 
select * from (select top 100 * from [dbo].[NESTLEIND] order by [date] desc ) table160 union 
select * from (select top 100 * from [dbo].[NETWORK18] order by [date] desc ) table162 union 
select * from (select top 100 * from [dbo].[NFL] order by [date] desc ) table290 union 
select * from (select top 100 * from [dbo].[NH] order by [date] desc ) table409 union 
select * from (select top 100 * from [dbo].[NHPC] order by [date] desc ) table342 union 
select * from (select top 100 * from [dbo].[NIACL] order by [date] desc ) table455 union 
select * from (select top 100 * from [dbo].[NILKAMAL] order by [date] desc ) table27 union 
select * from (select top 100 * from [dbo].[NLCINDIA] order by [date] desc ) table57 union 
select * from (select top 100 * from [dbo].[NMDC] order by [date] desc ) table329 union 
select * from (select top 100 * from [dbo].[NOCIL] order by [date] desc ) table112 union 
select * from (select top 100 * from [dbo].[NTPC] order by [date] desc ) table251 union 
select * from (select top 100 * from [dbo].[OBEROIRLTY] order by [date] desc ) table362 union 
select * from (select top 100 * from [dbo].[OFSS] order by [date] desc ) table77 union 
select * from (select top 100 * from [dbo].[OIL] order by [date] desc ) table343 union 
select * from (select top 100 * from [dbo].[OMAXE] order by [date] desc ) table310 union 
select * from (select top 100 * from [dbo].[ONGC] order by [date] desc ) table18 union 
select * from (select top 100 * from [dbo].[ORIENTCEM] order by [date] desc ) table393 union 
select * from (select top 100 * from [dbo].[ORIENTELEC] order by [date] desc ) table468 union 
select * from (select top 100 * from [dbo].[ORIENTREF] order by [date] desc ) table380 union 
select * from (select top 100 * from [dbo].[PAGEIND] order by [date] desc ) table300 union 
select * from (select top 100 * from [dbo].[PEL] order by [date] desc ) table1 union 
select * from (select top 100 * from [dbo].[PERSISTENT] order by [date] desc ) table355 union 
select * from (select top 100 * from [dbo].[PETRONET] order by [date] desc ) table240 union 
select * from (select top 100 * from [dbo].[PFC] order by [date] desc ) table295 union 
select * from (select top 100 * from [dbo].[PFIZER] order by [date] desc ) table117 union 
select * from (select top 100 * from [dbo].[PGHH] order by [date] desc ) table174 union 
select * from (select top 100 * from [dbo].[PGHL] order by [date] desc ) table113 union 
select * from (select top 100 * from [dbo].[PHILIPCARB] order by [date] desc ) table114 union 
select * from (select top 100 * from [dbo].[PHOENIXLTD] order by [date] desc ) table305 union 
select * from (select top 100 * from [dbo].[PIDILITIND] order by [date] desc ) table124 union 
select * from (select top 100 * from [dbo].[PIIND] order by [date] desc ) table370 union 
select * from (select top 100 * from [dbo].[PNB] order by [date] desc ) table100 union 
select * from (select top 100 * from [dbo].[PNBHOUSING] order by [date] desc ) table427 union 
select * from (select top 100 * from [dbo].[PNCINFRA] order by [date] desc ) table400 union 
select * from (select top 100 * from [dbo].[POLYCAB] order by [date] desc ) table486 union 
select * from (select top 100 * from [dbo].[POLYMED] order by [date] desc ) table378 union 
select * from (select top 100 * from [dbo].[POLYPLEX] order by [date] desc ) table121 union 
select * from (select top 100 * from [dbo].[POWERGRID] order by [date] desc ) table315 union 
select * from (select top 100 * from [dbo].[POWERINDIA] order by [date] desc ) table500 union 
select * from (select top 100 * from [dbo].[PRAJIND] order by [date] desc ) table122 union 
select * from (select top 100 * from [dbo].[PRESTIGE] order by [date] desc ) table363 union 
select * from (select top 100 * from [dbo].[PRSMJOHNSN] order by [date] desc ) table123 union 
select * from (select top 100 * from [dbo].[PSPPROJECT] order by [date] desc ) table436 union 
select * from (select top 100 * from [dbo].[PTC] order by [date] desc ) table241 union 
select * from (select top 100 * from [dbo].[PVR] order by [date] desc ) table264 union 
select * from (select top 100 * from [dbo].[QUESS] order by [date] desc ) table418 union 
select * from (select top 100 * from [dbo].[RADICO] order by [date] desc ) table230 union 
select * from (select top 100 * from [dbo].[RAIN] order by [date] desc ) table330 union 
select * from (select top 100 * from [dbo].[RAJESHEXPO] order by [date] desc ) table226 union 
select * from (select top 100 * from [dbo].[RALLIS] order by [date] desc ) table149 union 
select * from (select top 100 * from [dbo].[RAMCOCEM] order by [date] desc ) table210 union 
select * from (select top 100 * from [dbo].[RATNAMANI] order by [date] desc ) table276 union 
select * from (select top 100 * from [dbo].[RAYMOND] order by [date] desc ) table39 union 
select * from (select top 100 * from [dbo].[RBLBANK] order by [date] desc ) table423 union 
select * from (select top 100 * from [dbo].[RCF] order by [date] desc ) table150 union 
select * from (select top 100 * from [dbo].[RECLTD] order by [date] desc ) table331 union 
select * from (select top 100 * from [dbo].[REDINGTON] order by [date] desc ) table294 union 
select * from (select top 100 * from [dbo].[RELAXO] order by [date] desc ) table372 union 
select * from (select top 100 * from [dbo].[RELIANCE] order by [date] desc ) table37 union 
select * from (select top 100 * from [dbo].[RITES] order by [date] desc ) table472 union 
select * from (select top 100 * from [dbo].[RVNL] order by [date] desc ) table484 union 
select * from (select top 100 * from [dbo].[SAIL] order by [date] desc ) table38 union 
select * from (select top 100 * from [dbo].[SANOFI] order by [date] desc ) table151 union 
select * from (select top 100 * from [dbo].[SBICARD] order by [date] desc ) table499 union 
select * from (select top 100 * from [dbo].[SBILIFE] order by [date] desc ) table447 union 
select * from (select top 100 * from [dbo].[SBIN] order by [date] desc ) table40 union 
select * from (select top 100 * from [dbo].[SCHAEFFLER] order by [date] desc ) table148 union 
select * from (select top 100 * from [dbo].[SCHNEIDER] order by [date] desc ) table383 union 
select * from (select top 100 * from [dbo].[SCI] order by [date] desc ) table147 union 
select * from (select top 100 * from [dbo].[SEQUENT] order by [date] desc ) table412 union 
select * from (select top 100 * from [dbo].[SFL] order by [date] desc ) table429 union 
select * from (select top 100 * from [dbo].[SHILPAMED] order by [date] desc ) table346 union 
select * from (select top 100 * from [dbo].[SHOPERSTOP] order by [date] desc ) table256 union 
select * from (select top 100 * from [dbo].[SHREECEM] order by [date] desc ) table62 union 
select * from (select top 100 * from [dbo].[SHRIRAMCIT] order by [date] desc ) table254 union 
select * from (select top 100 * from [dbo].[SIEMENS] order by [date] desc ) table36 union 
select * from (select top 100 * from [dbo].[SIS] order by [date] desc ) table443 union 
select * from (select top 100 * from [dbo].[SJVN] order by [date] desc ) table356 union 
select * from (select top 100 * from [dbo].[SKFINDIA] order by [date] desc ) table220 union 
select * from (select top 100 * from [dbo].[SOBHA] order by [date] desc ) table289 union 
select * from (select top 100 * from [dbo].[SOLARA] order by [date] desc ) table471 union 
select * from (select top 100 * from [dbo].[SOLARINDS] order by [date] desc ) table274 union 
select * from (select top 100 * from [dbo].[SONATSOFTW] order by [date] desc ) table165 union 
select * from (select top 100 * from [dbo].[SOUTHBANK] order by [date] desc ) table53 union 
select * from (select top 100 * from [dbo].[SPARC] order by [date] desc ) table309 union 
select * from (select top 100 * from [dbo].[SPICEJET] order by [date] desc ) table490 union 
select * from (select top 100 * from [dbo].[SRF] order by [date] desc ) table166 union 
select * from (select top 100 * from [dbo].[SRTRANSFIN] order by [date] desc ) table167 union 
select * from (select top 100 * from [dbo].[STAR] order by [date] desc ) table231 union 
select * from (select top 100 * from [dbo].[STARCEMENT] order by [date] desc ) table439 union 
select * from (select top 100 * from [dbo].[STLTECH] order by [date] desc ) table59 union 
select * from (select top 100 * from [dbo].[SUDARSCHEM] order by [date] desc ) table260 union 
select * from (select top 100 * from [dbo].[SUMICHEM] order by [date] desc ) table497 union 
select * from (select top 100 * from [dbo].[SUNDARMFIN] order by [date] desc ) table169 union 
select * from (select top 100 * from [dbo].[SUNDRMFAST] order by [date] desc ) table137 union 
select * from (select top 100 * from [dbo].[SUNPHARMA] order by [date] desc ) table35 union 
select * from (select top 100 * from [dbo].[SUNTECK] order by [date] desc ) table345 union 
select * from (select top 100 * from [dbo].[SUNTV] order by [date] desc ) table275 union 
select * from (select top 100 * from [dbo].[SUPPETRO] order by [date] desc ) table170 union 
select * from (select top 100 * from [dbo].[SUPRAJIT] order by [date] desc ) table253 union 
select * from (select top 100 * from [dbo].[SUPREMEIND] order by [date] desc ) table168 union 
select * from (select top 100 * from [dbo].[SUVENPHAR] order by [date] desc ) table498 union 
select * from (select top 100 * from [dbo].[SUZLON] order by [date] desc ) table262 union 
select * from (select top 100 * from [dbo].[SWANENERGY] order by [date] desc ) table385 union 
select * from (select top 100 * from [dbo].[SWARAJENG] order by [date] desc ) table171 union 
select * from (select top 100 * from [dbo].[SWSOLAR] order by [date] desc ) table491 union 
select * from (select top 100 * from [dbo].[SYMPHONY] order by [date] desc ) table371 union 
select * from (select top 100 * from [dbo].[SYNGENE] order by [date] desc ) table402 union 
select * from (select top 100 * from [dbo].[TASTYBITE] order by [date] desc ) table434 union 
select * from (select top 100 * from [dbo].[TATACHEM] order by [date] desc ) table32 union 
select * from (select top 100 * from [dbo].[TATACOFFEE] order by [date] desc ) table142 union 
select * from (select top 100 * from [dbo].[TATACOMM] order by [date] desc ) table159 union 
select * from (select top 100 * from [dbo].[TATACONSUM] order by [date] desc ) table437 union 
select * from (select top 100 * from [dbo].[TATAELXSI] order by [date] desc ) table161 union 
select * from (select top 100 * from [dbo].[TATAINVEST] order by [date] desc ) table60 union 
select * from (select top 100 * from [dbo].[TATAMOTORS] order by [date] desc ) table34 union 
select * from (select top 100 * from [dbo].[TATAMTRDVR] order by [date] desc ) table338 union 
select * from (select top 100 * from [dbo].[TATAPOWER] order by [date] desc ) table43 union 
select * from (select top 100 * from [dbo].[TATASTEEL] order by [date] desc ) table44 union 
select * from (select top 100 * from [dbo].[TATASTLBSL] order by [date] desc ) table386 union 
select * from (select top 100 * from [dbo].[TCIEXP] order by [date] desc ) table430 union 
select * from (select top 100 * from [dbo].[TCNSBRANDS] order by [date] desc ) table474 union 
select * from (select top 100 * from [dbo].[TCS] order by [date] desc ) table249 union 
select * from (select top 100 * from [dbo].[TEAMLEASE] order by [date] desc ) table411 union 
select * from (select top 100 * from [dbo].[TECHM] order by [date] desc ) table281 union 
select * from (select top 100 * from [dbo].[THERMAX] order by [date] desc ) table163 union 
select * from (select top 100 * from [dbo].[THYROCARE] order by [date] desc ) table414 union 
select * from (select top 100 * from [dbo].[TIINDIA] order by [date] desc ) table452 union 
select * from (select top 100 * from [dbo].[TIMKEN] order by [date] desc ) table288 union 
select * from (select top 100 * from [dbo].[TITAN] order by [date] desc ) table41 union 
select * from (select top 100 * from [dbo].[TORNTPHARM] order by [date] desc ) table144 union 
select * from (select top 100 * from [dbo].[TORNTPOWER] order by [date] desc ) table286 union 
select * from (select top 100 * from [dbo].[TRENT] order by [date] desc ) table158 union 
select * from (select top 100 * from [dbo].[TRIDENT] order by [date] desc ) table134 union 
select * from (select top 100 * from [dbo].[TTKPRESTIG] order by [date] desc ) table215 union 
select * from (select top 100 * from [dbo].[TV18BRDCST] order by [date] desc ) table291 union 
select * from (select top 100 * from [dbo].[TVSMOTOR] order by [date] desc ) table58 union 
select * from (select top 100 * from [dbo].[TVTODAY] order by [date] desc ) table239 union 
select * from (select top 100 * from [dbo].[UBL] order by [date] desc ) table336 union 
select * from (select top 100 * from [dbo].[UCOBANK] order by [date] desc ) table234 union 
select * from (select top 100 * from [dbo].[UFLEX] order by [date] desc ) table143 union 
select * from (select top 100 * from [dbo].[UJJIVAN] order by [date] desc ) table415 union 
select * from (select top 100 * from [dbo].[UJJIVANSFB] order by [date] desc ) table496 union 
select * from (select top 100 * from [dbo].[ULTRACEMCO] order by [date] desc ) table248 union 
select * from (select top 100 * from [dbo].[UNIONBANK] order by [date] desc ) table219 union 
select * from (select top 100 * from [dbo].[UPL] order by [date] desc ) table218 union 
select * from (select top 100 * from [dbo].[VAIBHAVGBL] order by [date] desc ) table247 union 
select * from (select top 100 * from [dbo].[VAKRANGEE] order by [date] desc ) table273 union 
select * from (select top 100 * from [dbo].[VARROC] order by [date] desc ) table473 union 
select * from (select top 100 * from [dbo].[VBL] order by [date] desc ) table428 union 
select * from (select top 100 * from [dbo].[VENKEYS] order by [date] desc ) table155 union 
select * from (select top 100 * from [dbo].[VGUARD] order by [date] desc ) table332 union 
select * from (select top 100 * from [dbo].[VINATIORGA] order by [date] desc ) table341 union 
select * from (select top 100 * from [dbo].[VIPIND] order by [date] desc ) table156 union 
select * from (select top 100 * from [dbo].[VMART] order by [date] desc ) table391 union 
select * from (select top 100 * from [dbo].[VOLTAS] order by [date] desc ) table153 union 
select * from (select top 100 * from [dbo].[VRLLOG] order by [date] desc ) table399 union 
select * from (select top 100 * from [dbo].[VSTIND] order by [date] desc ) table216 union 
select * from (select top 100 * from [dbo].[VTL] order by [date] desc ) table154 union 
select * from (select top 100 * from [dbo].[WABCOINDIA] order by [date] desc ) table337 union 
select * from (select top 100 * from [dbo].[WELCORP] order by [date] desc ) table64 union 
select * from (select top 100 * from [dbo].[WELSPUNIND] order by [date] desc ) table236 union 
select * from (select top 100 * from [dbo].[WESTLIFE] order by [date] desc ) table489 union 
select * from (select top 100 * from [dbo].[WHIRLPOOL] order by [date] desc ) table339 union 
select * from (select top 100 * from [dbo].[WIPRO] order by [date] desc ) table42 union 
select * from (select top 100 * from [dbo].[WOCKPHARMA] order by [date] desc ) table145 union 
select * from (select top 100 * from [dbo].[YESBANK] order by [date] desc ) table259 union 
select * from (select top 100 * from [dbo].[ZEEL] order by [date] desc ) table152 union 
select * from (select top 100 * from [dbo].[ZENSARTECH] order by [date] desc ) table135 union 
select * from (select top 100 * from [dbo].[ZYDUSWELL] order by [date] desc ) table344) asd
order by ticker, [date] desc")
}
# sam_df_All <- update_top_hundred_tables()
# sam_df_All =  sam_df_All %>% distinct(ticker, date, .keep_all=TRUE)
# sam_df_All <- sam_df_All[!is.na(sam_df_All$openlow), ]
# sam_df_All_positive <- sam_df_All %>% group_by(ticker) %>% summarise(max_date = max(date))
# # View(sam_df_All_positive)
# sam_df_All_positive$openlow <- sam_df_All$openlow[match(sam_df_All_positive$max_date, sam_df_All$date)]

